Objetivo 2
evaanngiil/WishfulGiving pull request #18
Opened 2024-11-17 16:10 UTC by pablotl0

Sobre la estructura del repositorio

* [x] ¿He seguido las mejores prácticas en el nombre de las clases y ficheros y
   disposición de los mismos?
* [x] ¿He mirado tanto reglas generales (para cualquier repo) como reglas
específicas para el lenguaje con el que se está trabajando?

Sobre el planteamiento

* [x] ¿Se han planteado una serie de issues, asignados a las historias de
usuario pertinentes, que clarifiquen qué es lo que necesitan los usuarios e
identifiquen las diferentes partes del problema?
* [x] ¿Los issues representan un problema, y no una tarea?

Sobre el análisis del problema

* [x] ¿Se ha documentado qué análisis se ha hecho sobre el dominio para decir lo
   que se ha creado?
* [x] ¿Se ha documentado por qué se ha elegido que lo creado sea un objeto valor,
   una entidad o un agregado?
* [x] ¿He propuesto un producto mínimamente viable, que en muchos casos será un solo
   objeto valor que no dependa de ningún otro (y que sea la base de muchos
   otros)?.

Sobre el código

* [x] ¿Todos los mensajes de commit explican el cambio, y no se
      limitan a repetir el nombre del fichero que se ha cambiado?
* [x] ¿Los mensajes de commit siguen el formato estándar y buenas prácticas?
* [x] ¿Se ha hecho una revisión real del código para comprobar que todos
   los atributos y funciones creadas están respaldadas por una HU?
* [x] ¿Todos los issues creados están relacionados con a una HU?
* [x] ¿Ha asignado el propietario/la propietaria del repositorio todos los
issues planteados al *milestone* correspondiente?
* [x] ¿Todos los cambios en el código están asignados a un issue al que se
      referencia en un commit?
* [x] ¿Se ha asignado al mismo milestone el PR que se ha hecho?
* [x] ¿Es el milestone sobre el que estoy trabajando un producto
   mínimamente viable? ¿O tengo que solicitar al product manager que precise de
   qué producto se trata?
* [x] ¿Se ha comprobado que el código entregado sea sintácticamente
correcto?

Lista de comprobación para el propietario/a del repositorio

* [ ] ¿Los issues que ha planteado la persona son efectivamente problemas y
evidencian comprensión de las historias de usuario? Si no es así, es mejor que
se le transmita antes de que empiece a crear cualquier código erróneo.
* [ ] ¿Has comprobado que efectivamente el compañero/a ha seguido *su* lista de
      comprobación?
* [ ] ¿El código creado es una modelización válida de las historias de usuario
      creadas por ti, y te sirve como base para programar la lógica de negocio?
* [ ] ¿El código creado sigue las mejores prácticas para el lenguaje de
      programación que hayáis consensuado, tanto en identificadores, como
      nombres de ficheros, como disposición de los diferentes ficheros en el
      repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
      aportan código para resolver el problema planteado en el mismo?
* [ ] ¿He comprobado que el código compile, o que quien lo ha programado ha lo
ha hecho y documentado en el repositorio?
* [ ] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
correspondiente, que será el primero?
* [ ] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
el objetivo 4 para poder programar la lógica de negocio?
* [ ] En resumen, ¿considero que con lo hecho puedo ponerme a trabajar
directamente en el siguiente milestone, que incluye la lógica de negocio?

2024-11-17 16:42 UTC, evaanngiil commented
Por mi parte considero que todo está correcto, siguiendo la definición de modelo y sus características.

2024-11-17 16:56 UTC, evaanngiil approved these changes

2024-11-17 16:57 UTC, pablotl0 commented
@JJ revision

2024-11-18 12:16 UTC, evaanngiil commented
* [x] ¿Los issues que ha planteado la persona son efectivamente problemas y
evidencian comprensión de las historias de usuario? Si no es así, es mejor que
se le transmita antes de que empiece a crear cualquier código erróneo.
* [x] ¿Has comprobado que efectivamente el compañero/a ha seguido *su* lista de
      comprobación?
* [x] ¿El código creado es una modelización válida de las historias de usuario
      creadas por ti, y te sirve como base para programar la lógica de negocio?
* [x] ¿El código creado sigue las mejores prácticas para el lenguaje de
      programación que hayáis consensuado, tanto en identificadores, como
      nombres de ficheros, como disposición de los diferentes ficheros en el
      repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
      aportan código para resolver el problema planteado en el mismo?
* [x] ¿He comprobado que el código compile, o que quien lo ha programado ha lo
ha hecho y documentado en el repositorio?
* [x] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
correspondiente, que será el primero?
* [x] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
el objetivo 4 para poder programar la lógica de negocio?
* [x] En resumen, ¿considero que con lo hecho puedo ponerme a trabajar
directamente en el siguiente milestone, que incluye la lógica de negocio?

2024-11-19 08:28 UTC, pablotl0 commented
@JJ listo para revision

2024-11-19 12:32 UTC, JJ commented
> Por mi parte considero que todo está correcto, siguiendo la definición de modelo y sus características.

Evan, es prácticamente imposible que esté todo correcto a la primera. Ni siquiera los profesionales que trabajan en una empresa lo consiguen. Por favor, mira bien lo que hace, mira bien los errores frecuentes (que hay un buen montón) y vuelve a revisar.

2024-11-22 11:57 UTC, pablotl0 commented
@JJ listo para revision

2024-11-22 12:25 UTC, pablotl0 commented
@JJ listo para revisión.

2024-11-22 12:33 UTC, evaanngiil approved these changes
El modelo resuelve los requerimientos de la HU asociada al milestone 0. Además, el objeto valor esta separado de la entidad. Lo doy por aprobado

2024-11-28 09:19 UTC, JJ requested changes
Por favor, consulta los errores comunes también.

2024-11-28 09:19 UTC, JJ commented on src/usuario.java
> +public class Usuario {
¿Y quién maneja los diferentes usuarios?
¿Necesitarás una entidad?

2024-11-28 09:19 UTC, JJ commented on src/ListaDeseos.java
> +    private ArrayList<Producto> deseos;
¿Qué valor añade al cliente ponerle un nombre diferente a un array?

2024-11-28 12:20 UTC, pablotl0 commented
@evaanngiil listo para revision

2024-11-28 15:06 UTC, evaanngiil requested changes
El objeto valor `Producto` es manejado por la entidad `Usuario`, a su vez esta es manejada por la entidad principal `GestorDeUsuarios`. Sin embargo, creo que si la entidad se llama `GestorDeUsuarios` no tiene mucho sentido llamar al archivo _sistema_

2024-11-28 15:24 UTC, pablotl0 commented
@evaanngiil ya he corregido el error.

2024-11-28 15:35 UTC, evaanngiil requested changes
Recuerda también seguir las buenas prácticas de programación usando _snake_case_ o _camelCase_ (usa el que creas conveniente) en el renombrado de los archivos de Java. Lo ideal sería no mezclar ambos tipos de convenciones

2024-11-29 11:15 UTC, pablotl0 commented
@evaanngiil ya he cambiado el nombre de los archivos

2024-11-29 11:43 UTC, evaanngiil approved these changes

2024-11-29 11:51 UTC, pablotl0 commented
@evaanngiil he cambiado la estructura del gestor de Usuarios para facilitar la búsqueda de estos. En relación con los errores comunes.

2024-11-29 12:33 UTC, pablotl0 commented
@JJ listo para revision

2024-11-29 12:34 UTC, evaanngiil approved these changes

2024-12-02 06:41 UTC, JJ commented
> Recuerda también seguir las buenas prácticas de programación usando _snake_case_ o _camelCase_ (usa el que creas conveniente) en el renombrado de los archivos de Java. Lo ideal sería no mezclar ambos tipos de convenciones

En realidad, cada lenguaje de programación tiene su propia convención. No puedes usar "el que creas conveniente" (salvo que en Java sea así)

2024-12-02 06:47 UTC, JJ requested changes
El principal el problema aquí es no resolver bien el comentario, sin modificar el código sobre el que se comenta o decir en qué commit se hace. Pero el problema mayor es aprobar el PR sin entender muy bien qué es lo que hace y por qué.

2024-12-02 06:47 UTC, JJ commented on src/gestorDeUsuarios.java
> +    private HashMap<String, Usuario> usuarios; // Cambiado a HashMap
No se usan comentarios en código limpio y menos para indicar qué se ha hecho. Para eso están los mensajes de commit.

2024-12-02 06:47 UTC, JJ commented on src/gestorDeUsuarios.java
> +    public GestorDeUsuarios() {
Tener que ir al commit específico para ver qué se hace no ayuda a revisar. En la primera línea del mensaje de commit tiene que haber algo más que el número del issue.

2024-12-02 06:47 UTC, JJ commented on src/gestorDeUsuarios.java
> +    private HashMap<String, Usuario> usuarios; // Cambiado a HashMap
¿Qué es la clave aquí?

2024-12-02 06:47 UTC, JJ commented on src/usuario.java
> +public class Usuario {
No se cierran *nunca* los comentarios sin decir por qué.
Si en este caso la respuesta es #16 y a "como se manejan los usuarios" creas un "manejador de usuarios" es que no has entendido demasiado bien la pregunta ni estás haciendo un modelo adecuado.

2024-12-02 09:30 UTC, pablotl0 commented on src/gestorDeUsuarios.java
> +    private HashMap<String, Usuario> usuarios; // Cambiado a HashMap
La clave en este caso seria un String refiriéndose al nombre del usuario.

2024-12-02 09:42 UTC, pablotl0 commented on src/usuario.java
> +public class Usuario {
@JJ La entidad me sirve para administrar los usuarios,  asegurando de que la lógica se maneje de manera centralizada.  Ya que el HashMap solo almacena datos y no define cómo se usan ni gestiona la lógica de los datos.

2024-12-02 09:55 UTC, pablotl0 commented on src/gestorDeUsuarios.java
> +    public GestorDeUsuarios() {
@JJ He modificado el mensaje del commit 900f1550. 
Explicando que es necesario una entidad para gestionar la lógica del conjunto de usuarios

2024-12-02 13:59 UTC, pablotl0 commented
@JJ revision

2024-12-02 16:29 UTC, JJ requested changes
Aparte de tener que resolver *todos* los comentarios, una vez más @evaanngiil tendría que replantearse si el modelo es correcto y suficiente para programar la lógica de negocio.

2024-12-02 16:29 UTC, JJ commented on src/gestorDeUsuarios.java
> +    public GestorDeUsuarios() {
El comentario sigue sin resolver y sigue sin estar justificada la existencia de esta clase específica.

2024-12-02 16:29 UTC, JJ commented on src/producto.java
> +        this.nombre = nombre.trim();
¿Por qué haces `trim`?

2024-12-02 16:29 UTC, JJ commented on src/usuario.java
> +    private ArrayList<Producto> listaDeseos;
@evaanngiil ¿esto cubre la historia de usuario?

2024-12-02 16:41 UTC, evaanngiil commented on src/usuario.java
> +    private ArrayList<Producto> listaDeseos;
Al tratarse de un usuario que va a recibir regalos creo que faltaría información para cubrir la lógica de negocio y resolver la HU #4. ¿Qué pasaría si pido unas zapatillas o una prenda de ropa? Con la información que contiene `Producto` no bastaría para resolver el problema

2024-12-02 18:18 UTC, pablotl0 commented on src/usuario.java
> +    private ArrayList<Producto> listaDeseos;
@JJ yo puedo añadir mas atributos pero si en la historia de usuario no se referencian esas necesidades entonces no es un producto mínimo ya que me estoy inventando atributos. ¿Qué atributos son los necesarios realmente?

2024-12-02 18:43 UTC, pablotl0 commented on src/gestorDeUsuarios.java
> +    public GestorDeUsuarios() {
@JJ En el mensaje del commit 8cfe218 se explica porque debe existir la clase

2024-12-02 18:43 UTC, pablotl0 commented
@JJ revision

2024-12-02 19:20 UTC, JJ commented on src/usuario.java
> +    private ArrayList<Producto> listaDeseos;
Voy a comentar en la HU

2024-12-02 19:23 UTC, JJ commented on src/usuario.java
> +    private ArrayList<Producto> listaDeseos;
Por otro lado, con esta estructura de datos no garantizas una fuente única de verdad para los productos.

2024-12-02 23:17 UTC, pablotl0 commented
@evaanngiil revision

2024-12-03 15:31 UTC, evaanngiil commented on src/Presupuesto.java
> +    private double presupuestoRestante;
La clase Presupuesto no se va a utilizar en ninguna otra ocasión por lo que no sé porqué se encuentra separado. Además, no veo necesario crear una clase para un presupuesto el cual puede ser simplemente un valor flotante.

2024-12-03 15:37 UTC, evaanngiil requested changes

2024-12-03 15:37 UTC, evaanngiil commented on src/Presupuesto.java
> +    private double presupuestoRestante;
La clase Presupuesto no se va a utilizar en ninguna otra ocasión por lo que no sé porqué se encuentra separado. Además, no veo necesario crear una clase para un presupuesto el cual puede ser simplemente un valor flotante.

2024-12-03 15:37 UTC, evaanngiil commented on src/ListaRegalos.java
> +        private final int prioridad;
Un elemento en la lista será un regalo con su prioridad asociada, es redundante crear una nueva clase para ello.

2024-12-03 15:37 UTC, evaanngiil commented on src/GestorListaRegalos.java
> +    private HashMap<String, ListaRegalos> listas;
¿Qué representa la clave del diccionario?

2024-12-03 18:16 UTC, pablotl0 commented
@evaanngiil ya he corregido los cambios

2024-12-03 18:19 UTC, pablotl0 commented on src/GestorListaRegalos.java
> +    private HashMap<String, ListaRegalos> listas;
hace referencia al destinatario de la lista de regalos

2024-12-03 18:46 UTC, evaanngiil requested changes

2024-12-03 18:46 UTC, evaanngiil commented on src/Regalo.java
> +
Creo que el atributo `nombre` no incluiría información completa del regalo a hacer. Si bien creo que que lo más adecuando sería un `título` genérico y una `descripción`donde se diga de forma más específica las condiciones y detalles del regalo (como la talla, el color, el tamaño, etc)

2024-12-03 18:54 UTC, pablotl0 commented
@evaanngiil Ya está actualizado

2024-12-03 18:55 UTC, evaanngiil approved these changes
Ahora sí creo que cumple con el producto mínimamente viable requerido en #4

2024-12-03 18:57 UTC, pablotl0 commented
@JJ  Listo para revisión

2024-12-03 19:29 UTC, JJ approved these changes
:+1:

2024-12-03 22:03 UTC, merged