[IV-24-25] Updating objetivo-0.md
evaanngiil/WishfulGiving pull request #2
Opened 2024-09-22 18:00 UTC by evaanngiil

Revertida el merge de la rama

2024-09-23 05:33 UTC, JJ commented
El PR debe incluir en el cuerpo la lista de comprobación.

2024-09-23 06:53 UTC, evaanngiil commented
Se me olvidó, no se me escribió automáticamente como en el anterior PR. ¿Lo abro de nuevo?

2024-09-23 06:57 UTC, JJ commented
Simplemente edita. Y noese escribe automáticamente aquí en tu repo, solo en el mío

2024-09-26 07:00 UTC, evaanngiil commented
@JJ revisión

2024-09-26 09:47 UTC, evaanngiil commented
Cierro pull request ya que he realizado nuevos cambios en el proyecto? @JJ

2024-09-26 10:05 UTC, JJ commented
Los cambios aparecerán como commits añadidos a la rama, para eso está el PR. El PR en tu repo no se cierra, se fusiona cuando yo lo apruebe.

2024-09-26 10:10 UTC, evaanngiil commented
ok, entendido, te comunico sin mas los cambios realizados desde el mismo PR.

2024-09-28 08:20 UTC, JJ requested changes
La descripción sigue siendo muy escasa y sigues sin incluir y enlazar la configuración del repositorio.

2024-10-04 10:47 UTC, closed without merging