[IV-2024-2025] Objetivo 4
evaanngiil/WishfulGiving pull request #26
Opened 2024-12-19 19:06 UTC by evaanngiil

* [ ]  ¿Hay un camino claro que permita ir desde el código hasta la historia de
   usuario que desarrolla, pasando por el mensaje de commit y el issue
   correspondiente?
* [ ]  ¿Se ha intentado cubrir con tests una parte de la lógica de negocio que se
   esté desarrollando?
* [ ]  ¿Hay un producto mínimamente viable que describa lo que se va a entregar en
   este objetivo?
* [ ]  ¿En este producto mínimamente viable se han priorizado unas clases,
   módulos o paquetes más fundamentales frente a otros, movidos a otro
   PMV/Hito?
* [ ] ¿Estoy leyendo todo lo que marco o simplemente marco lo que se me pone por
delante?
* [ ] ¿Se han documentado las elecciones de biblioteca de aserciones y del
   de *test runner*?
* [ ] ¿Te has asegurado que lo que mencionas como biblioteca de aserciones y
test runners lo son realmente y tienen la misma funcionalidad? ¿O estás poniendo
`unittest` como *test runner* y `pytest` como biblioteca de aserciones?
* [ ] ¿Esa documentación incluye criterios de aceptación y también criterios de
búsqueda para las diferentes opciones?
* [ ]  ¿Se han seguido los principios F.I.R.S.T. en la creación del test y
   se ha documentado cómo se ha hecho?
* [ ]  ¿Se describe claramente en el PMV los tests que hay que pasar para que se
   considere viable?
* [ ] ¿Se han testeado también las excepciones?

2024-12-29 08:50 UTC, juanbarearojo reviewed
Buenas se me ha asignado tu pr para corregir. Te dejo comentarios para que mejores

2024-12-29 08:50 UTC, juanbarearojo commented on src/test/java/com/example/WishfulGiving/ListaRegalosTest.java
> +        ListaRegalos listaJuan = listas.get(0);
¿Has considerado alguna opción para evitar el uso de números mágicos ?

2024-12-29 08:50 UTC, juanbarearojo commented on src/test/java/com/example/WishfulGiving/ListaRegalosTest.java
> +        assertEquals(3, listaJuan.totalRegalos());
En general los test solo deberían probar una cosa

2024-12-29 08:50 UTC, juanbarearojo commented on src/main/java/com/example/WishfulGiving/ListaRegalos.java
> +    /**
En general cuando hablamos de código debería ser bastante claro para que no sean necesarios comentarios explicando lo que hace.

2024-12-29 08:50 UTC, juanbarearojo commented on src/main/java/com/example/WishfulGiving/ListaRegalos.java
> +        if (presupuesto < 0) {
Cuando ponemos condiciones de este estilo no solo es necesario comprobar en test cuando funcionan sino cuando no funcionan también es necesario comprobarlo

2024-12-29 08:50 UTC, juanbarearojo commented on docs/testing_testrunner.md
> +- **Facilidad de integración con herramientas de CI/CD.**
¿Como consideras que esto sea objetivo?

2024-12-29 08:50 UTC, juanbarearojo commented on docs/testing_testrunner.md
> +- **Impacto en la deuda técnica**
¿El impacto en la deuda tecnica es medible?

2024-12-29 08:50 UTC, juanbarearojo commented on docs/testing_testrunner.md
> +- **Soporte para paralelismo o concurrencia.**
¿Consideras que este criterio sea estrictamente necesario ?

2024-12-29 08:50 UTC, juanbarearojo commented on docs/testing_testrunner.md
> +TestNG es un framework avanzado diseñado para pruebas jerárquicas y más complejas. Ofrece soporte nativo para paralelismo y priorización, permitiendo definir dependencias entre tests y agruparlos med
En los criterios no mencionas nada sobre la complejidad. En ese caso porque lo pones en la descripción de la herramienta este hecho.

2024-12-29 08:50 UTC, juanbarearojo commented on docs/testing_testrunner.md
> +### Spock
En las descripciones de la herramientas es recomendable poner solo aquello que sea relevante para la elección

2024-12-29 08:50 UTC, juanbarearojo commented on docs/testing_testrunner.md
> +### Arquillian
¿Has considerado poner enlaces a las herramientas que usas? Es una de la ventajas de trabajar en un medio digital

2024-12-29 08:50 UTC, juanbarearojo commented on src/test/java/com/example/WishfulGiving/ListaRegalosTest.java
> +        assertThrows(IllegalArgumentException.class,
En general los constructores no deben ser probados. Pero en caso de que quieras hacerlo. Deberías testear todas las condiciones de este

2024-12-29 11:24 UTC, antoniorr02 reviewed
Buenas, en principio la revisión de @juanbarearojo la veo bastante exhaustiva con lo que hasta que no arregles lo que te propone no tengo mucho más que añadir, lo único que puedo decir es que en el cuerpo del PR hay una de las opciones sin marcar, deberías de marcar todas.

2024-12-30 02:00 UTC, evaanngiil commented on src/test/java/com/example/WishfulGiving/ListaRegalosTest.java
> +        assertThrows(IllegalArgumentException.class,
Resuelto en https://github.com/evaanngiil/WishfulGiving/pull/26/commits/7612eb2f326fb6b4cf8e5d8022373ce3af71eb9b

2024-12-30 02:00 UTC, evaanngiil commented on src/main/java/com/example/WishfulGiving/ListaRegalos.java
> +        if (presupuesto < 0) {
Resuelto en https://github.com/evaanngiil/WishfulGiving/pull/26/commits/7612eb2f326fb6b4cf8e5d8022373ce3af71eb9b

2024-12-30 02:02 UTC, evaanngiil commented on src/main/java/com/example/WishfulGiving/ListaRegalos.java
> +    /**
Como bien se indicó en el Objetivo 2, se debe documentar el código para facilitar la comprensión de las mismas, fomentando las buenas prácticas

2024-12-30 02:02 UTC, evaanngiil commented on src/test/java/com/example/WishfulGiving/ListaRegalosTest.java
> +        assertEquals(3, listaJuan.totalRegalos());
Resuelto en https://github.com/evaanngiil/WishfulGiving/pull/26/commits/7612eb2f326fb6b4cf8e5d8022373ce3af71eb9b

2024-12-30 02:02 UTC, evaanngiil commented on src/test/java/com/example/WishfulGiving/ListaRegalosTest.java
> +        ListaRegalos listaJuan = listas.get(0);
Resuelto en https://github.com/evaanngiil/WishfulGiving/pull/26/commits/7612eb2f326fb6b4cf8e5d8022373ce3af71eb9b

2024-12-30 02:03 UTC, evaanngiil commented on docs/testing_testrunner.md
> +### Arquillian
Resuelto en https://github.com/evaanngiil/WishfulGiving/pull/26/commits/5c9861ea9d857a6fe2967d266fb98c0f5e3cea8f

2024-12-30 02:03 UTC, evaanngiil commented on docs/testing_testrunner.md
> +### Spock
Resuelto en https://github.com/evaanngiil/WishfulGiving/pull/26/commits/5c9861ea9d857a6fe2967d266fb98c0f5e3cea8f

2024-12-30 02:03 UTC, evaanngiil commented on docs/testing_testrunner.md
> +TestNG es un framework avanzado diseñado para pruebas jerárquicas y más complejas. Ofrece soporte nativo para paralelismo y priorización, permitiendo definir dependencias entre tests y agruparlos med
Resuelto en https://github.com/evaanngiil/WishfulGiving/pull/26/commits/5c9861ea9d857a6fe2967d266fb98c0f5e3cea8f

2024-12-30 02:03 UTC, evaanngiil commented on docs/testing_testrunner.md
> +- **Soporte para paralelismo o concurrencia.**
Resuelto en https://github.com/evaanngiil/WishfulGiving/pull/26/commits/5c9861ea9d857a6fe2967d266fb98c0f5e3cea8f

2024-12-30 02:03 UTC, evaanngiil commented on docs/testing_testrunner.md
> +- **Impacto en la deuda técnica**
Resuelto en https://github.com/evaanngiil/WishfulGiving/pull/26/commits/5c9861ea9d857a6fe2967d266fb98c0f5e3cea8f

2024-12-30 02:03 UTC, evaanngiil commented on docs/testing_testrunner.md
> +- **Facilidad de integración con herramientas de CI/CD.**
Resuelto en https://github.com/evaanngiil/WishfulGiving/pull/26/commits/5c9861ea9d857a6fe2967d266fb98c0f5e3cea8f

2024-12-30 02:05 UTC, evaanngiil commented
@juanbarearojo @antoniorr02 Listo para revisión

2024-12-30 07:26 UTC, JLombar reviewed
Te he comentado un par de errores tontos y el tema de los comentarios aplícalo al resto de archivos que también los incluyen. En cualquier caso vas muy bien, suerte!

2024-12-30 07:26 UTC, JLombar commented on build.gradle
> +    // Dependencias para Jackson
No te recomiendo añadir comentarios si no son estrictamente necesarios, añaden deuda técnica y más trabajo al programador. Si no son parte de un milestone o algo así deberías borrarlos

2024-12-30 07:26 UTC, JLombar commented on settings.gradle
> +    // Apply the foojay-resolver plugin to allow automatic download of JDKs
Te digo lo mismo que antes

2024-12-30 07:26 UTC, JLombar commented on docs/testing_testrunner.md
> +El test runner es fundamental para ejecutar y organizar los tests que verifican la calidad de un software como se expresa en #29. En Java, existen varios frameworks que se pueden utilizar para realiz
Este documento está muy bien pero no pones en ningún momento una lista de requisitos o algo así no? Debería ser lo primero que hagas. En caso de que yo esté equivocado deberías cambiarlo, si no está mal.

2024-12-30 08:25 UTC, juanbarearojo reviewed
Estoy de acuerdo con @JLombar. El código debe ser creado con la intención de leído y a lo mejor algún día ser ejecutado. Si tienes en cuenta conceptos como no números mágicos, comentarios o complejidad de las funciones hace que sea mucha fácil mantener el código a largo plazo y facilita el trabajo de los revisores. Te recomiendo que cada vez que hagas código tengas esto en mente. Vas por buen camino.

2024-12-30 08:25 UTC, juanbarearojo commented on src/test/java/com/example/WishfulGiving/ListaRegalosTest.java
> +        assertEquals(50.0, presupuestoRestante, "El presupuesto restante no coincide con el presupuesto total.");
¿Has considerado usar variables para números que se repiten bastante ?

2024-12-30 13:35 UTC, evaanngiil commented on src/test/java/com/example/WishfulGiving/ListaRegalosTest.java
> +        assertEquals(50.0, presupuestoRestante, "El presupuesto restante no coincide con el presupuesto total.");
No veo necesario crear una variable para un número que se repite 2 veces

2024-12-30 13:38 UTC, evaanngiil commented on settings.gradle
> +    // Apply the foojay-resolver plugin to allow automatic download of JDKs
Resuelto en https://github.com/evaanngiil/WishfulGiving/pull/26/commits/08b2efa833092b01481bb99705373e05b5c76e07

2024-12-30 13:39 UTC, evaanngiil commented on build.gradle
> +    // Dependencias para Jackson
Resuelto en https://github.com/evaanngiil/WishfulGiving/pull/26/commits/ce7be3d5d4bde5c948161a1519f9a995d97fcfbb

2024-12-30 13:39 UTC, evaanngiil commented on docs/testing_testrunner.md
> +El test runner es fundamental para ejecutar y organizar los tests que verifican la calidad de un software como se expresa en #29. En Java, existen varios frameworks que se pueden utilizar para realiz
Resuelto en https://github.com/evaanngiil/WishfulGiving/pull/26/commits/721c3b862af7ff8d5e2310d297a1136ee3270436

2024-12-30 13:41 UTC, evaanngiil commented
@JLombar Listo para revisión

2025-01-02 07:50 UTC, juanbarearojo approved these changes

2025-01-02 09:11 UTC, antoniorr02 approved these changes

2025-01-02 10:41 UTC, evaanngiil commented
@JJ listo para revisión

2025-01-03 08:01 UTC, JJ requested changes
Aparte de lo indicado, tampoco se testea realmente que se cumpla #4, que es lo principal.

2025-01-03 08:01 UTC, JJ commented on docs/testing_aserciones.md
> +- Deben integrarse fácilmente con sistemas como Maven o Gradle, incluyendo soporte nativo para configuración y ejecución de pruebas.
¿hay alguna que no lo haga? Si no quieres que este criterior parezca una excusa, pon al menos una herramienta que realmente se use que no lo cumpla.

2025-01-03 08:01 UTC, JJ commented on docs/testing_aserciones.md
> +- **[AssertJ](https://assertj.github.io/doc)**, por otro lado, proporciona una API fluida que permite escribir pruebas altamente legibles, especialmente útil para objetos complejos. Sin embargo, segú
¿Qué es una API fluida?

2025-01-03 08:01 UTC, JJ commented on docs/testing_aserciones.md
> +- **[Hamcrest](https://github.com/hamcrest/JavaHamcrest)** es conocida por sus `Matchers` que permiten escribir pruebas expresivas. Sin embargo, las estadísticas de *GitHub* indican que su repositori
¿Qué es un "matcher"? ¿Qué es una prueba expresiva? ¿Es un criterio de los que hay arriba?

2025-01-03 08:01 UTC, JJ commented on docs/testing_aserciones.md
> +Se selecciona **JUnit 5** como biblioteca de aserciones debido a su integración nativa con herramientas estándar, su mantenimiento activo y su flexibilidad, cumpliendo con los criterios de evitar dep
¿Qué significa "integración nativa con herramientas estándar"? Si es que está incluida en la biblioteca estándar, dilo así.

2025-01-03 08:01 UTC, JJ commented on docs/testing_testrunner.md
> +Spock es un framework basado en *Groovy* que combina pruebas unitarias, funcionales y de comportamiento (BDD) en un único enfoque. Su sintaxis concisa y expresiva permite escribir pruebas de manera c
¿Qué significa "basado en Groovy"? ¿"Combinar pruebas unitarias" sería una descripción de un test runner o de una biblioteca de aserciones?

2025-01-03 08:01 UTC, JJ commented on docs/testing_testrunner.md
> +Destaca por su capacidad para manejar dependencias entre pruebas y ejecutar *suites* (conjuntos de tests agrupados) de manera jerárquica. Sin embargo, según las métricas de *GitHub*, tiene una activi
¿JUnit hace eso?

2025-01-03 08:01 UTC, JJ commented on docs/testing_testrunner.md
> +Arquillian está diseñado para pruebas de integración en aplicaciones *Java EE* o *Jakarta EE*. Permite ejecutar pruebas dentro de contenedores reales, como *WildFly* o *GlassFish*, simulando entornos
Por favor, poned exclusivamente las bibliotecas que correspondan a la funcionalidad que se pone.

2025-01-03 08:01 UTC, JJ commented on docs/testing_testrunner.md
> +Se elige **JUnit 5** como test runner principal por su simplicidad, soporte nativo en el ecosistema Java, mantenimiento activo y capacidad de satisfacer los requisitos comunes de pruebas. Para escena
¿Y con qué comando se ejecutan los tests? Si hay una forma estándar de hacerlo en el lenguaje, de todas formas hay que ponerlo.

2025-01-03 08:01 UTC, JJ commented on src/Regalo.java
Este commit no corresponde a ningún issue. ¿No sería más fácil crear un fichero dummy en vez de andar cambiando nombres para que pase los tests?

2025-01-03 08:01 UTC, JJ commented on src/main/java/com/example/WishfulGiving/JsonLoader.java
> +package com.example.WishfulGiving;
¿usar `example.com` como parte del nombre del package es una buena práctica?

2025-01-03 08:01 UTC, JJ commented on src/main/java/com/example/WishfulGiving/ListaRegalos.java
> +        if (presupuesto < 0) {
¿presupuesto 0 también es admisible?

2025-01-03 08:01 UTC, JJ commented on src/main/java/com/example/WishfulGiving/Regalo.java
> +        if (precio < 0) {
¿Gratis también es admisible?

2025-01-03 08:01 UTC, JJ commented on src/main/java/com/example/WishfulGiving/Regalo.java
> +        if (prioridad < 1 || prioridad > 5) {
No se deben usar números mágicos en el código, sólo constantes con nombre.

2025-01-03 08:01 UTC, JJ commented on src/main/java/com/example/WishfulGiving/Regalo.java
> +                throw new IllegalArgumentException("La prioridad debe estar entre 1 y 5.");
¿Este 1 es mismo de arriba? ¿Diferente? ¿Si se cambia la prioridad mínima cuantas cosas más habría que cambiar?

2025-01-03 08:01 UTC, JJ commented on src/main/java/com/example/WishfulGiving/Regalo.java
> +    public String getTitulo() {
¿Pide la HU todos estos getters?

2025-01-03 08:01 UTC, JJ commented on src/test/java/com/example/WishfulGiving/ListaRegalosTest.java
> +    void testEliminarRegaloExistente() {
¿las buenas prácticas dicen que hay que repetir "Test" en el nombre de la función y en la anotación?

2025-01-03 08:01 UTC, JJ commented on src/test/java/com/example/WishfulGiving/ListaRegalosTest.java
> +    void testCalcularPresupuestoRestanteSinRegalos() {
¿Esto testea comportamientos o se limita a ver si operaciones aritméticas han salido bien?

2025-01-03 08:01 UTC, JJ commented on src/main/java/com/example/WishfulGiving/ListaRegalos.java
> +    public List<Regalo> obtenerRegalosDentroPresupuesto(){
Esto lo has añadido en el commit https://github.com/evaanngiil/WishfulGiving/commit/31e8a30a331e4dda59eef7eb4e45ddc63f14a88a 
1. cuyo mensaje no tiene nada que ver con lo que haces (hace mucho más que la restricción de los atributos)
2. No tiene nada que ver con el issue #28 que referencia
3. No tiene nada que ver con #4 porque no *maximiza la satisfacción* con el presupuesto, simplemente asigna por orden de prioridad.

2025-01-11 19:32 UTC, evaanngiil commented on src/Regalo.java
No se a que se refiere con un fichero dummy. De todas formas el cambio de nombre es para que pase los test que ha puesto usted en el repositorio donde exige snake_case mientras que en java se requiere de CamelCase.

2025-01-11 19:57 UTC, JJ commented on src/Regalo.java
Un fichero que no sirve para nada y no tiene nada, en vez de un fichero real. En todo casi tienes que indicar el problema en un issue y resolverlo con un commit. Ya sé que lo has hecho por eso, lo que estoy cuestionando es como lo has hecho (sin issue, cambiando de nombre un fichero)

2025-01-11 19:58 UTC, evaanngiil commented on src/main/java/com/example/WishfulGiving/JsonLoader.java
> +package com.example.WishfulGiving;
No lo es tanto, lo adecuado sería usar un dominio real relacionado con el proyecto. Por ejemplo, si el proyecto pertenece a una organización con dominio wishfulgiving.com, el paquete debería ser com.wishfulgiving. En el proyecto no se da el caso por lo que lo he cambiado al nombre del proyecto como tal

2025-01-11 20:00 UTC, evaanngiil commented on src/main/java/com/example/WishfulGiving/ListaRegalos.java
> +        if (presupuesto < 0) {
Sí, es admisible ya que se puede crear una lista desde el inicio sin tener un presupuesto definido, será más tarde cuando se defina y se pueda cambiar ese valor

2025-01-11 20:07 UTC, evaanngiil commented on src/main/java/com/example/WishfulGiving/Regalo.java
> +        if (precio < 0) {
Sí, si bien es una lista de regalos estos no tienen porque ser algo material, se pueden poner tanto experiencias como cosas que no tengan un valor monetario

2025-01-11 20:26 UTC, evaanngiil commented on src/main/java/com/example/WishfulGiving/Regalo.java
> +    public String getTitulo() {
Sí, para implementar la lógica de negocio necesaria para resolver la HU se deben implementar esos getters.

2025-01-11 20:35 UTC, evaanngiil commented on src/Regalo.java
Disculpa, lo había entendido mal. Sí, totalmente, la metodología que seguí para resolver el problema no ha sido la adecuada. Para la próxima, podrías detallarme como se procedería a hacer con un archivo dummy?

2025-01-11 20:59 UTC, evaanngiil commented on src/main/java/com/example/WishfulGiving/ListaRegalos.java
> +    public List<Regalo> obtenerRegalosDentroPresupuesto(){
Si es cierto que el mensaje no refleja totalmente los cambios que hago. Pero también es cierto que si tiene que ver con el issue ya que se deben modificar la privacidad de algunos atributos y añadir anotaciones para poder resolver el problema planteado en el issue. Finalmente, también es cierto que el algoritmo planteado para maximizar la satisfacción con el presupuesto se queda corto a la necesidad que se plantea. En lineas generales no separé en varios issues el problema que resolvía, uno para la lógica de negocio y otro para solucionar el problema de repetición de código con Jackson. Ahora lo cambio

2025-01-12 13:01 UTC, JJ commented on src/main/java/com/example/WishfulGiving/ListaRegalos.java
> +    public List<Regalo> obtenerRegalosDentroPresupuesto(){
A estas alturas ya deberíais saber que no hace falta explicar nada, simplemente hacer el cambio que se estime conveniente y explicar en el mensaje de commit o, si acaso, en un issue que se cree para resolver el problema que se indique.

2025-01-12 13:03 UTC, JJ commented on src/main/java/com/example/WishfulGiving/ListaRegalos.java
> +        if (presupuesto < 0) {
En general, la buena práctica es que cuando se cree un objeto tenga todo lo necesario para crearse; si no se tiene, tienes que comprobar *en cada uno de los pasos y métodos* si es correcto. O sea que no se debería poder definir una lista hasta que no tenga un presupuesto definido.

2025-01-12 13:04 UTC, JJ commented on src/main/java/com/example/WishfulGiving/Regalo.java
> +        if (precio < 0) {
1. Se indica que este comentario está outdated. Si el cambio tiene algo que ver con la respuesta, ¿para qué lo pones en vez de ponerlo en el mensaje de commit? Si no tiene nada que ver con la respuesta, ¿para qué la pones?
2. ¿Eso viene en la historia de usuario en la que estás trabajando?

2025-01-12 13:30 UTC, evaanngiil commented
@JJ Listo para revisión

2025-01-12 17:31 UTC, evaanngiil commented on src/main/java/com/example/WishfulGiving/Regalo.java
> +        if (precio < 0) {
En la HU no se especifica eso en concreto, se generaliza como regalo pero no se llega a tanto nivel de detalle. Quería responderle al comentario para que viera porqué no he hecho ningun cambio en relación a este problema, por aclarar el motivo.

2025-01-12 17:34 UTC, evaanngiil commented on src/main/java/com/example/WishfulGiving/ListaRegalos.java
> +        if (presupuesto < 0) {
Con presupuesto definido a que han llegado a un acuerdo para poner un presupuesto X (no se refiere a tener definido el campo `presupuesto`. El campo presupuesto puede tener 0 en lo que llega el usuario a esa conclusion. De todas formas lo cambio para que no pueda ser 0

2025-01-12 17:37 UTC, evaanngiil commented
@JJ  Listo para revision

2025-01-14 09:45 UTC, JJ requested changes
El principal problema es que no estás testeando la historia de usuario #4. El resto de los problemas se podrían resumir en: Java. Ninguno de ellos bloquea la aprobación, pero sí te agradecería qu elos abordaras en la medida de lo posible.

2025-01-14 09:45 UTC, JJ commented on docs/testing_aserciones.md
> +- Evitar la dependencia de liberías externas. Es decir, se priorizan herramientas nativas o ampliamente adoptadas en el ecosistema estándar de Java para reducir la complejidad y la deuda técnica.
`liberias`

2025-01-14 09:45 UTC, JJ commented on docs/testing_aserciones.md
> +- Se consideran herramientas con métricas objetivas de mantenimiento, tales como actividad reciente en el repositorio (commits en el último año), volumen de contribuciones y número de versiones estab
La última es objetiva, las otras son más bien arbitrarias. ¿Una herramienta madura que ya esté estable va a tener commits el último año?

2025-01-14 09:45 UTC, JJ commented on docs/testing_aserciones.md
> +- **[JUnit 5](https://github.com/junit-team/junit5)** se destaca como una biblioteca de aserciones integrada con su test runner estándar. De acuerdo con su repositorio oficial en *GitHub*, ha recibid
Por favor, limitaros a poner lo relacionado con los criterios. ¿Crees que decir qué aserciones tiene añade alguna información a tu proceso de decisión?

2025-01-14 09:45 UTC, JJ commented on docs/testing_aserciones.md
> +- **[Hamcrest](https://github.com/hamcrest/JavaHamcrest)**  aunque fue ampliamente utilizado en el pasado, ha perdido relevancia frente a JUnit 5 y AssertJ. Tiene baja actividad en su repositorio de
Si de lo que estás hablando es de configuración adicional de Maven y Gradle (o de la herramienta que hayas elegido) dilo así explícitamente.

2025-01-14 09:45 UTC, JJ commented on docs/testing_aserciones.md
> +## Elección de Biblioteca de Aserciones
¿Seguro que no hay más librerías? Yo he encontrado varias en la primera página de Google.

2025-01-14 09:45 UTC, JJ commented on docs/testing_aserciones.md
> +# Testing en Java - Aserciones
¿Se escribe *aserciones*?

Por otro lado, estoy viendo que en Java existe algo llamado Testing Engine. JUnit 5 tiene algo llamado "Jupiter", pero existe también uno anterior llamado "Vintage". También estoy viendo otros diferentes, que son la base de otras bibliotecas (como estas de JUnit).

Quizás deberías comentar también en qué consisten estos testing engines y tratar de elegir uno (porque lo estás haciendo de todas formas)

2025-01-14 09:45 UTC, JJ commented on docs/testing_aserciones.md
> +Se selecciona **JUnit 5** como biblioteca de aserciones debido a que esta incluida en la biblioteca estándar de Java, a su mantenimiento activo y su flexibilidad, y a que cumple con los criterios de
En [esta página](https://junit.org/junit5/docs/current/user-guide/#running-tests) pone como configurar "dependencias adicionales en Gradle y Maven". ¿Necesita o no necesita dependencias adicionales?

2025-01-14 09:45 UTC, JJ commented on docs/testing_testrunner.md
> +JUnit 5 es el estándar en Java para la ejecución de pruebas. Según su repositorio en GitHub, cuenta con alta actividad de mantenimiento, con múltiples contribuciones activas y al menos dos versiones
Estoy viendo que `@Tag` son precisamente anotaciones para el *engine*, así que más razón para hablar de él. Sí podías haber hablado de cosas como `@BeforeEach` con lo que no tendría que haber mirado la documentación de JUnit para ver si efectivament es un test runner o no. Aquí se trata por un lado que mostréis que conocéis las herramientas disponibles, pero sobre todo que demostréis que entendéis bien los conceptos con los que estáis tratando de tomar una decisión. Y el problema es que si se trata de un ecosistema con el que tengo poca familiaridad como el de Java, tenéis que ayudar un poco más con esto.
Al final, se trata de que se vea claro que habéis tomado una decisión correcta con los elementos correctos y los conceptos correctos. Por eso, si tenéis que añadir información que creéis que el profesor no tiene, la añadís. Si sobra ya os lo diré.

2025-01-14 09:45 UTC, JJ commented on docs/testing_testrunner.md
> +Aunque popular, su adopción ha disminuido frente a JUnit 5..  Según las métricas de *GitHub*, tiene una actividad algo menor en comparación con JUnit y podría no ajustarse a proyectos estándar debido
¿Qué es un "proyecto estándar"? ¿Es eso un criterio?

2025-01-14 09:45 UTC, JJ commented on docs/testing_testrunner.md
> +Su uso está enfocado en proyectos que utilizannel lenguaje Groovy, lo que lo hace menos adecuado para Java puro. Cuenta con una actividad al nivel de JUnit 5 en *GitHub*, con versiones recientes lanz
typo

2025-01-14 09:45 UTC, JJ commented on docs/testing_testrunner.md
> +### [Spock](https://github.com/spockframework/spock)
En la documentación dice "testing and specificacion framework". Los specs son equivalentes a un grupo de test. Pero me he tenido que meter en la documentación y preguntarle a Grok la diferencia entre "spec" y "matcher". He aprendido bastante, pero de veras que me resultaría más sencillo que me ayudárais con estas cosas sobre todo si tenéis familiaridad con el lenguaje. En todo caso, parece que funciona perfectamente con Java puro.

2025-01-14 09:45 UTC, JJ commented on docs/testing_testrunner.md
> +En el caso de Java, lo habitual para compilar y ejecutar los tests es usar las herramientas estándar integradas en los sistemas de construcción como Maven o Gradle. Sin embargo, Gradle se destaca por
Pero creo que para que lo haga tienes que definir el Test Engine, como te digo arriba, al menos en JUnit es así. Estaría bien que hicieras referencia a eso.

2025-01-14 09:45 UTC, JJ commented on settings.gradle
> +    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
???

2025-01-14 09:45 UTC, JJ commented on settings.gradle
> +    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
Estoy viendo que está relacionado con el #27 (por cierto, la convención de 50 caracteres en la primera línea con el número de issue delante ahorraría muchos clicks). Sin embargo, no planteas ningún problema específico relacionado con este plugin, ni por qué has elegido este y no otro, con lo que es casi imposible evaluar, para alguien como yo, si has tomado una buena decisión o no. ¿Hay más opciones? ¿Son opciones que hay que considerar dentro de las decisiones de arriba, como las bibliotecas de aserciones?

2025-01-14 09:45 UTC, JJ commented on src/main/java/WishfulGiving/JsonLoader.java
> + * Utiliza la biblioteca Jackson: https://github.com/FasterXML/jackson
En general, *hay que documentar cada decisión*, inclusive esta. Incluso el hecho de que *haya que tomar una decisión*. Si se trata de leer listas, lo más sencillo habría sido simplemente usar listas de texto. Se trata siempre de buscar *el producto mínimamente viable*

2025-01-14 09:45 UTC, JJ commented on src/main/java/WishfulGiving/JsonLoader.java
> +            throw new RuntimeException("Error al leer el archivo JSON: " + e.getMessage(), e);
¿Qué archivo JSON? Los errores deben siempre contener toda la información posible para poder arreglarlos

2025-01-14 09:45 UTC, JJ commented on src/main/java/WishfulGiving/ListaRegalos.java
> +    public String getDestinatario() {
¿La historia de usuario pide todos estos getters?

2025-01-14 09:45 UTC, JJ commented on src/main/java/WishfulGiving/ListaRegalos.java
> +    public void agregarRegalo (Regalo regalo) {
¿La lista de usuario pide esto? ¿O con tener la lista de regalos ya se aplica? Ten en cuenta que estás en el *producto mínimamente viable*, no en *todo lo que voy a necesitar cuando meta aquí el UI con Angullar*

2025-01-14 09:45 UTC, JJ commented on src/main/java/WishfulGiving/ListaRegalos.java
> +        // Ordenar los regalos por relación prioridad/precio de forma descendente.
¿Crees que es necesario el docstring arriba *y* esto? En código limpio no hacen falta comentarios en línea, solo los necesarios para generar documentación (o para el IDE)

2025-01-14 09:45 UTC, JJ commented on src/main/java/WishfulGiving/Regalo.java
> +    public int getPrioridad() {
¿Esto lo pide la HU?

2025-01-14 09:45 UTC, JJ commented on src/main/java/WishfulGiving/ListaRegalos.java
> +        for (Regalo regalo : regalosOrdenados) {
Estás usando un algoritmo greedy en vez de un problema de la mochila para solucionarlo. Eso hace que maximices la prioridad, pero no que maximices el número de regalos para el presupuesto. No sé si eso respetará la historia de usuario.

2025-01-14 09:45 UTC, JJ commented on src/test/java/WishfulGiving/ListaRegalosTest.java
> +    void obtenerRegalosDentroDelPresupuesto() {
La HU habla de #4 "maximizar satisfacción". Eso es lo que hay que testear, no que se ha aplicado la función correctamente. 
Ya comenté en el objetivo 2 que testear "máxima satisfacción" tiene que implicar que hay otro método de asignación, el que sea, y que no obtiene la misma.

2025-01-14 12:14 UTC, evaanngiil commented on src/main/java/WishfulGiving/JsonLoader.java
> + * Utiliza la biblioteca Jackson: https://github.com/FasterXML/jackson
Con documentar a que te refieres, hay un issue abierto y ahi no puedo poner la solucion a ese issue. Por lo que se me ocurre en comentarios del propio código.

2025-01-14 16:28 UTC, evaanngiil commented on settings.gradle
> +    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
Cierto que no lo he expuesto en el issue, esa decision la tomó directamente el IDE por si solo cuando cree el proyecto con Gradle y JUnit 5. He estado investigando y he encontrado que recientemente Gradle ha sacado su propia API nativa para la gestion de versiones y toolchains en Java desde la version Gradle 6.7 (cosa que ya tenia implementada desde un inicio por recomendacion de la propia documentacion de Gradle, pero en fin NetBeans y sus cosas). 

Por otro lado, he actualizado el issue #27 describiendo mas detalladamente el problema. Te hago un commit a ese issue actualizado con una nueva implementacion.

2025-01-14 16:34 UTC, evaanngiil commented on docs/testing_aserciones.md
> +- Se consideran herramientas con métricas objetivas de mantenimiento, tales como actividad reciente en el repositorio (commits en el último año), volumen de contribuciones y número de versiones estab
Siempre se puede tratar de sacar nuevas versiones y crear nuevas funcionalidades en la herramienta. También suelen surgir bugs a lo largo del año, se valora que se solucionen y esten constantemente actualizandose.

2025-01-14 16:53 UTC, evaanngiil commented on docs/testing_aserciones.md
> +## Elección de Biblioteca de Aserciones
Cuando investigué no encontre mas librerias que utilicen aserciones como tal. Si es cierto que hay librerias para hacer testing como indica [este link] (https://www.yunielacosta.com/posts/es/boost-your-java-testing-with-these-7-incredible-libraries/) que me aparece el primero tras buscar librerias de aserciones en Google.

Pero como librerias de aserciones como tal no encuentro mas que las que estan puestas y la anterior que elimine ya que es pensado para contenedores. Se explica detalladamente [aqu](https://www.arquitecturajava.com/java-assert-librerias-y-enfoques/)

2025-01-14 17:18 UTC, evaanngiil commented on docs/testing_aserciones.md
> +# Testing en Java - Aserciones
Sí, eso ya lo habia tenido en cuenta desde el principio como se puede ver en el `build.gradle` donde existe una dependencia que es Jupiter, base para que JUnit funcione.

Haré mención al concepto de testing engine. Suele ser uno definido por biblioteca, no hay mucho para elegir ni dudar entre varios.

2025-01-14 17:46 UTC, evaanngiil commented on docs/testing_testrunner.md
> +En el caso de Java, lo habitual para compilar y ejecutar los tests es usar las herramientas estándar integradas en los sistemas de construcción como Maven o Gradle. Sin embargo, Gradle se destaca por
sí es necesario y obligatorio definir el test engine para ejecutar los test con el test runner. Eso lo di por sabido cuando menciono que requiere de herramientas de construcción. Lo detallo mas especificamente

2025-01-14 17:54 UTC, evaanngiil commented on docs/testing_testrunner.md
> +### [Spock](https://github.com/spockframework/spock)
Son equivalentes a los Suites sí. Eso son conceptos que estudié antes de realizar la documentación pero no vi necesario detallarlos ya que pensaba que teníamos que ceñirnos a los criterios. 
Por otro lado, si funciona perfectamente con Java puro, pero dificulta su uso con Java puro se ve dificultado debido a esa dependencia de Groovy (no es práctico mezclar lenguajes).

2025-01-14 19:15 UTC, evaanngiil commented
@JJ  Listo para revisión.

PD: Llevo toda la tarde con el objetivo, he tratado de detallarlo lo máximo posible para dejar claro todos los conceptos, si ves que hay algo que sobra dímelo. He hecho como UDP, best-effort 😅

2025-01-14 19:56 UTC, JJ commented on src/main/java/WishfulGiving/JsonLoader.java
> + * Utiliza la biblioteca Jackson: https://github.com/FasterXML/jackson
**Desde el objetivo 2** se os ha dicho que *los mensajes de commit son para la documentación*.
¿Seguro? ¿No se puede poner regalo;prioridad;precio y no tienes que añadir una dependencia?

2025-01-14 20:00 UTC, evaanngiil commented on src/main/java/WishfulGiving/JsonLoader.java
> + * Utiliza la biblioteca Jackson: https://github.com/FasterXML/jackson
Cierto, disculpa por no haberlo recordado. Sí se podría, lo tendré en cuenta para la próxima, gracias por mencionar la idea.

2025-01-17 08:20 UTC, JJ requested changes
Los comentarios se resuelven *siempre* con un cambio, que se debe indicar. Si es una respuesta, quien tiene que decidir si está resuelto o no es *quien ha puesto el comentario*.

2025-01-17 08:20 UTC, JJ commented on README.md
> +Además, en este [otro](docs/testing_testrunner.md) encontrarás los criterios utilizados para elegir a `JUnit 5` como test-runner y a `Gradle`como herramienta CLI.
Gradle sigue siendo un sistema de construcción que puede hacer también tareas. Para que Gradle sea herramienta CLI de test, tienes que definir un TestEngine; Gradle no sabe hacer tests por sí mismo. Por lo menos eso es lo que yo he entendido.

2025-01-17 08:20 UTC, JJ commented on build.gradle
> +    // Jackson para manejo de JSON
¿Sigues usando JSON?

2025-01-17 08:20 UTC, JJ commented on build.gradle
> +        languageVersion = JavaLanguageVersion.of(23)
Aquí estás haciendo un cambio fundamental en tu proyecto, subiendo 6 la versión de Java. Este cambio lo cambia todo, **y no lo estás justificando**. En el commit que lo cambia,  83fbc2e8420ebec4ebbcc53c813662271910f212, dices algo sobre los tests y referencias el #27, relacionado con la "herramienta CLI". ¿Te parece que ese commit e issue justifiquen suficientemente este cambio *fundamental*, que además vas a tener que llevar hacia adelante todo el proyecto?
Por otro lado, imagino que la razón por la que has hecho esto es por el Jackson este del JSON. Sea por él, sea por cualquier otra biblioteca, ¿no te parece que debería ser un criterio para su elección las versiones de Java que soporta?

2025-01-17 08:20 UTC, JJ commented on build.gradle
> +    useJUnitPlatform()
Estoy viendo [aquí](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/testing/Test.html) que  Gradle tiene órdenes también para TestNG, por lo que el criterio de integración también lo cumpliría, ¿no?

2025-01-17 08:20 UTC, JJ commented on docs/testing_aserciones.md
> +# Testing en Java - Aserciones
No sé qué diablos pensaba cuand puse lo de "aserciones". Por supuesto que se dice aserciones.
Anyway.
Sí hay para elegir entre ambos, y te puse ejemplos; JUnit5 tiene al menos 2. Tú has elegido Jupiter, pero podrías haber elegido el otro.

2025-01-17 08:20 UTC, JJ commented on docs/testing_aserciones.md
> +- Evitar la dependencia de librerías externas. Es decir, se priorizan herramientas nativas o ampliamente adoptadas en el ecosistema estándar de Java para reducir la complejidad y la deuda técnica.
"nativas" no es lo mismo que "ampliamente adoptadas". Si lo que tienen en común es que tengan un interfaz sencillo en Gradle, tienes al menos dos que lo cumplen, por lo que puedo ver, TestNG, pero también JUnit *en dos versiones*, 4 y 5.

2025-01-17 08:20 UTC, JJ commented on docs/testing_aserciones.md
> +- Se consideran herramientas con métricas objetivas de mantenimiento, tales como actividad reciente en el repositorio (commits en el último año), volumen de contribuciones y número de versiones estab
Y *siempre* hay que resolver con un commit. A estas alturas deberías saberlo.
Como esto es algo básico desde el objetivo 2, paro aquí.

2025-01-17 09:18 UTC, evaanngiil commented on README.md
> +Además, en este [otro](docs/testing_testrunner.md) encontrarás los criterios utilizados para elegir a `JUnit 5` como test-runner y a `Gradle`como herramienta CLI.
Sí, eso se especifica dentro de la documentación del test runner. Por eso ahí pongo que Gradle la usamos como herramienta CLI de test

2025-01-17 09:19 UTC, evaanngiil commented on build.gradle
> +    // Jackson para manejo de JSON
Sí, nunca lo había hecho para construir objetos y me hace ilusión dejarlo, en otra ocasión que surja tendré muy en cuenta la versión con un vector

2025-01-17 09:22 UTC, evaanngiil commented on build.gradle
> +        languageVersion = JavaLanguageVersion.of(23)
Sí, hay muchas bibliotecas modernas que no han sido diseñadas para versiones antiguas por lo que toca subir la versión. Es completamente cierto que no referencio el motivo del cambio ni lo dejo claro. Como bien te comenté pensaba que los commits eran algo más genérico, siento el error.

2025-01-17 09:22 UTC, JJ commented on README.md
> +Además, en este [otro](docs/testing_testrunner.md) encontrarás los criterios utilizados para elegir a `JUnit 5` como test-runner y a `Gradle`como herramienta CLI.
Sigue sin ser herramienta CLI de test, sino una herramienta que permite definir un TestEngine, que tiene el "rol" equivalente al CLI de test. No has *elegido* gradle como CLI de test, el que hayas elegido Gradle en el 3 ha condicionado que elijas una forma determinada de hacer los tests usando TestEngines (y el resto)

2025-01-17 09:24 UTC, JJ commented on build.gradle
> +    // Jackson para manejo de JSON
¿Te parece que "me hace ilusión dejarlo" es una buena justificación para una decisión técnica, o más bien la misma definición de deuda técnica?

2025-01-17 09:24 UTC, evaanngiil commented on build.gradle
> +    useJUnitPlatform()
Sí, pero como se ve [aquí](https://www.swtestacademy.com/how-to-use-testng-with-gradle/) es mucho más tedioso configurarlo ya que requiere de archivos adicionales para las suites entre otras cosas.

2025-01-17 09:26 UTC, JJ commented on build.gradle
> +        languageVersion = JavaLanguageVersion.of(23)
En muchos casos, hay que usar forzosamente versiones antiguas, sobre todo en aplicaciones Android, donde la versión del teléfono incluirá una versión u otra, en algunos casos muy antiguas. En una aplicación cliente servidor no es el caso, pero debéis aprender que cambiar la versión del lenguaje de un proyecto simplemente *no se hace* y menos por acomodar una dependencia; si acaso, es una decisión previa que se toma en función de la infraestructura que se pueda soportar y las decisiones sobre dependencias se toman en base a eso.

2025-01-17 09:27 UTC, evaanngiil commented on docs/testing_aserciones.md
> +# Testing en Java - Aserciones
No, es JUnit quien tiene 2, Jupiter para la versión **5** y Vintage para las versiones *3 y 4*. En la documentación los explico

2025-01-17 09:28 UTC, evaanngiil commented on docs/testing_aserciones.md
> +- Se consideran herramientas con métricas objetivas de mantenimiento, tales como actividad reciente en el repositorio (commits en el último año), volumen de contribuciones y número de versiones estab
Estaba resuelto @JJ desde el momento que te envié el commit. Desde el objetivo 2 trato de asegurarme que todos esten resueltos, ruego me lo continue corrigiendo

2025-01-17 09:30 UTC, JJ commented on build.gradle
> +    useJUnitPlatform()
Eso es para añadir la suite. ¿Tienes que definirlo obligatoriamente?

2025-01-17 09:33 UTC, evaanngiil commented on build.gradle
> +        languageVersion = JavaLanguageVersion.of(23)
No lo sabía, creía que si no afectaba a ninguna otra dependencia podría implementar el cambio de versión. Si es cierto que en proyectos grandes eso es algo muy dificil de hacer ya que seguramente salten errores por todos lados por dependencias y otros aspectos

2025-01-17 09:33 UTC, JJ commented on docs/testing_aserciones.md
> +# Testing en Java - Aserciones
A ver. Lo que yo he entendido es que puedes usar Vintage *desde JUnit 5* si quieres ejecutar los tests *de la versión 4* o test "legacy". Por lo tanto, tienes para elegir, dependiendo de las aserciones, todas válidas, que tengas. En la documentación de JUnit viene así.

2025-01-17 09:35 UTC, JJ commented on build.gradle
> +        languageVersion = JavaLanguageVersion.of(23)
No hay proyectos grandes y pequeños, hay buenas prácticas que debes tratar de aprender e interiorizar cualquiera que sea el tipo de proyecto. Y una de ellas es "La versión es importante". Ya lo verás también en el 5 y el 6.

2025-01-17 09:39 UTC, evaanngiil commented on docs/testing_aserciones.md
> +# Testing en Java - Aserciones
¿No crees que eso añade deuda técnica? A mi por lo menos no se me vendría a la cabeza hacer algo así en mi proyecto pudiendo usar dierectamente o la version 4 enteramente con su test engine o la 5 con el suyo propio

2025-01-17 09:41 UTC, evaanngiil commented on build.gradle
> +    useJUnitPlatform()
No lo tienes que definir, peor si quieres aprovechar las ventajas que te proporciona TestNG frente a JUnit si lo tienes que definir ya que no solo añade la suite. Define grupos de tests, las suites, controla la paralelización, define dependencias entre tests, configura los listeners y los parámetros que se le pasan a los tests. ¿No crees que es mucho más engorroso que JUnit y por eso se dice que requiere configuración adicional?

2025-01-17 09:44 UTC, evaanngiil commented on build.gradle
> +    // Jackson para manejo de JSON
no lo es, de verdad que me parece mucho más engorroso estar cambiandolo todo para poder usar vectores. Te justifico el porqué lo uso y aprendo los motivos para no usarlo la próxima vez.

2025-01-17 09:53 UTC, evaanngiil commented on README.md
> +Además, en este [otro](docs/testing_testrunner.md) encontrarás los criterios utilizados para elegir a `JUnit 5` como test-runner y a `Gradle`como herramienta CLI.
Gradle es una herramienta de automatización de la construcción que se utiliza principalmente a través de una CLI. Si bien delega la ejecución de los tests a los TestEngines, se utiliza como CLI para iniciar y configurar la ejecución de los tests.El comando ./gradlew test es un claro ejemplo de cómo Gradle se utiliza como una herramienta CLI para ejecutar tests, incluso cuando la ejecución real la realizan los TestEngines.

Por lo tanto, es correcto decir que Gradle es una herramienta CLI para testing, en el sentido de que proporciona la interfaz de línea de comandos y el entorno para configurar y ejecutar las pruebas, aunque no las ejecute directamente.
 Justificando esto el añadir una herramienta CLI que ejecute únicamente test sin necesidad de un test engine hace que se añada deuda técnica, una misma herramienta para todo proceso de construcción donde nos aseguremos que cumple la función de CLI es lo más adecuado

2025-01-17 09:54 UTC, JJ commented on docs/testing_aserciones.md
> +# Testing en Java - Aserciones
No se trata de que lo *uses*. Se trata de que documentes que hay varias posibilidades y que justifiques la que estás eligiendo.

2025-01-17 09:59 UTC, evaanngiil commented on docs/testing_aserciones.md
> +# Testing en Java - Aserciones
Ya lo he hecho en 252968d9dda66f45649be1bab0dedd1f45d7486f. Pero si quieres lo amplio. Hazmelo saber

2025-01-17 10:01 UTC, JJ commented on build.gradle
> +    useJUnitPlatform()
No se trata de lo que yo crea o no. En mi caso particular, cuando has dicho "paralelización" me han hecho los ojos chiribitas, porque me acuerdo en la empresa donde trabajaba que tardaban los tests de Kotlin 20 minutos (aunque no tenían ni un test unitario, la verdad).
Lo que quiero decir es
1. ¿Esas ventajas pueden ser criterios?
2. Si no usas esas ventajas y por lo tanto *no tienes que hacer ningún tipo de configuración adicional*, TestNG cumpliría el criterio igual que TestNG, ¿no?

En estos criterios (como en todos) se trata simplemente de que seáis honestos en el proceso de elección que habéis seguido, no que pongáis los criterios *a posteriori* cargando las tintas sobre el que ya habéis elegido. Puede haber perfectamente dos o tres herramientas que cumplan los criterios a la perfección, en cuyo caso al final es un *judgment call*: elijo esta. Ni siquiera tienes que justificarlo. Pero lo que no puedes hacer es ocultar información sobre otras que no has elegido o poner excusas externas a los criterios para no haberlo hecho.

2025-01-17 10:01 UTC, evaanngiil commented
Buenas @JJ qué pasaría si un mensaje no implica ningún cambio y se responde con una justificación directamente ¿debo no resolverlo? Eso ha sido lo que ha pasado en uno de los recientes mensajes donde lo acabé resolviendo.

2025-01-17 10:03 UTC, JJ commented on build.gradle
> +    // Jackson para manejo de JSON
No se trata de que lo justifiques. **Es que no puedes usar ninguna biblioteca externa**, ni siquiera aunque sea periférica a la lógica de negocio. Usa vectores o lo que te dé la gana, pero sin bibliotecas externas.

2025-01-17 10:04 UTC, JJ commented on README.md
> +Además, en este [otro](docs/testing_testrunner.md) encontrarás los criterios utilizados para elegir a `JUnit 5` como test-runner y a `Gradle`como herramienta CLI.
No, no es una herramienta CLI de test y ni siquiera existe ese concepto en el ecosistema Java.

2025-01-17 10:04 UTC, JJ commented
> Buenas @JJ qué pasaría si un mensaje no implica ningún cambio y se responde con una justificación directamente ¿debo no resolverlo? Eso ha sido lo que ha pasado en uno de los recientes mensajes donde lo acabé resolviendo.

¿Pues que igual es una falta de respeto cerrar como resuelto un comentario a la persona que te lo ha hecho? ¿No te parece que debería ser esa persona la que lo cerrara?

2025-01-17 10:40 UTC, evaanngiil commented
Sí, totalmente, es una falta de respeto. Lo había entendido completamente al revés, que yo como dueño del repo podía resolver los comentarios por eso siempre los resuelvo yo. Te pido perdón

2025-01-17 10:56 UTC, evaanngiil commented on build.gradle
> +    useJUnitPlatform()
Si lo cumple pero haría la misma función que JUnit, por lo que por ello se utiliza la biblioteca estándar y nativa de Java.
Entiendo tu punto para la elección de la biblioteca siguiendo los criterios, sin embargo, en otros comentarios me sugeriste que uno de los criterios que ponía los cumplía todas las bibliotecas y que por ende debía añadir una herramienta o biblioteca que NO lo cumpliera.

2025-01-17 11:01 UTC, JJ commented
> Sí, totalmente, es una falta de respeto. Lo había entendido completamente al revés, que yo como dueño del repo podía resolver los comentarios por eso siempre los resuelvo yo. Te pido perdón

No pasa nada. No hablaba de mi caso en particular, sino en general de la acción. En mi caso, va con el hecho de que la gente tiene que aprender, no nace aprendida.

2025-01-17 11:03 UTC, JJ commented on build.gradle
> +    useJUnitPlatform()
No veo como tiene algo que ver con esto, pero en todo caso, lo que te he dicho al principio tendrías que seguirlo. Trata de poner *todos* los criterios que hayas seguido, y no descartes bibliotecas por criterios que *no* hayas indicado.

2025-01-17 11:55 UTC, evaanngiil commented on README.md
> +Además, en este [otro](docs/testing_testrunner.md) encontrarás los criterios utilizados para elegir a `JUnit 5` como test-runner y a `Gradle`como herramienta CLI.
Lo cambio a lo que propones

2025-01-17 15:05 UTC, evaanngiil commented
@JJ Listo para revisión.

2025-01-18 09:39 UTC, JJ requested changes
El problema principal es no haber cerrado en muchos casos, ni incorrectamente ni correctamente, los comentarios; pero también revisando he visto algún problema adicional.

2025-01-18 09:39 UTC, JJ commented on build.gradle
> +        languageVersion = JavaLanguageVersion.of(23)
Esto sigue sin resolverse. Siempre tienes que resolver todos los comentarios.

2025-01-18 09:39 UTC, JJ commented on build.gradle
> +    useJUnitPlatform()
Si has hecho algún cambio en los criterios que se pueda considerar respuesta aquí, por favor indícalo.

2025-01-18 09:39 UTC, JJ commented on docs/testing_aserciones.md
> +# Testing en Java - Aserciones
Este puedes resolverlo.

2025-01-18 09:39 UTC, JJ commented on docs/testing_aserciones.md
> +- Se consideran herramientas con métricas objetivas de mantenimiento, tales como actividad reciente en el repositorio (commits en el último año), volumen de contribuciones y número de versiones estab
Si no has hecho ningún cambio, no está resuelto.

2025-01-18 09:39 UTC, JJ commented on docs/testing_aserciones.md
> +## Elección de Biblioteca de Aserciones
Indica en qué commit lo has hecho.

2025-01-18 09:39 UTC, JJ commented on docs/testing_testrunner.md
> +TestNG, aunque popular en el pasado, ha visto una disminución en su adopción frente a JUnit 5 en proyectos Java típicos y según las métricas de *GitHub*, tiene una actividad algo menor en comparación
¿TestNG tiene aserciones? ¿Debería incluirse en ese apartado?

2025-01-18 11:58 UTC, evaanngiil commented on build.gradle
> +    useJUnitPlatform()
Se ha corregido añadiendo un nuevo criterio aquí https://github.com/evaanngiil/WishfulGiving/pull/26/commits/9af16bafd1e69b5c683c233124cb2b957918fda8

2025-01-18 12:00 UTC, evaanngiil commented on build.gradle
> +    // Jackson para manejo de JSON
Se añade nueva funcionalidad para leer datos de un archivo de texto delimitado, eliminamos deuda técnica eliminando dependencias externas, lo puedes ver en https://github.com/evaanngiil/WishfulGiving/pull/26/commits/801ce5019f8f80b39ad7f7e368d43f99a18f5d1e

2025-01-18 12:01 UTC, evaanngiil commented on README.md
> +Además, en este [otro](docs/testing_testrunner.md) encontrarás los criterios utilizados para elegir a `JUnit 5` como test-runner y a `Gradle`como herramienta CLI.
Se indica que no existe el concepto de herramienta CLI en Java y se especifica qué papel tiene Gradle en https://github.com/evaanngiil/WishfulGiving/pull/26/commits/a5ac2726bc2829e46997cb0d13abaccfb68c5b69

2025-01-18 12:03 UTC, evaanngiil commented on docs/testing_aserciones.md
> +## Elección de Biblioteca de Aserciones
Se eliminala dependencia de la librería Guava que añadi con animo de hacer pruebas. Se indica en https://github.com/evaanngiil/WishfulGiving/pull/26/commits/f9efdc13ac531d79d18792ead6423ff1287da2d3

2025-01-18 12:09 UTC, evaanngiil commented on docs/testing_aserciones.md
> +- Evitar la dependencia de librerías externas. Es decir, se priorizan herramientas nativas o ampliamente adoptadas en el ecosistema estándar de Java para reducir la complejidad y la deuda técnica.
Se resuelve en https://github.com/evaanngiil/WishfulGiving/pull/26/commits/585ee254e0b8f4da1f33f58bf7c44df55ce8e098

2025-01-18 14:35 UTC, evaanngiil commented on docs/testing_testrunner.md
> +TestNG, aunque popular en el pasado, ha visto una disminución en su adopción frente a JUnit 5 en proyectos Java típicos y según las métricas de *GitHub*, tiene una actividad algo menor en comparación
Sí, proporciona una biblioteca de aserciones que puede ser nombrada en la documentacion propia. Pero también actua como test runner (como JUnit)

2025-01-18 14:52 UTC, evaanngiil commented on build.gradle
> +        languageVersion = JavaLanguageVersion.of(23)
Se resuelve en https://github.com/evaanngiil/WishfulGiving/pull/26/commits/591180babe3e0139c50015ebce0655e7127dd166

2025-01-18 14:53 UTC, evaanngiil commented on docs/testing_aserciones.md
> +- Se consideran herramientas con métricas objetivas de mantenimiento, tales como actividad reciente en el repositorio (commits en el último año), volumen de contribuciones y número de versiones estab
Se resuelve en https://github.com/evaanngiil/WishfulGiving/pull/26/commits/0fbe00d6500d16133b5429d42f0e014a1f3fbf3b . Añadiendo especificacion en el criterio del mantenimiento de la herramienta

2025-01-18 14:54 UTC, evaanngiil commented on docs/testing_testrunner.md
> +TestNG, aunque popular en el pasado, ha visto una disminución en su adopción frente a JUnit 5 en proyectos Java típicos y según las métricas de *GitHub*, tiene una actividad algo menor en comparación
Lo resuelvo en https://github.com/evaanngiil/WishfulGiving/pull/26/commits/9a27665962ef9d730d194498d59cdec4d09d197a

2025-01-18 14:56 UTC, evaanngiil commented on docs/testing_aserciones.md
> +# Testing en Java - Aserciones
Lo resolví en https://github.com/evaanngiil/WishfulGiving/commit/252968d9dda66f45649be1bab0dedd1f45d7486f
Donde indico los diferentes test engines que existen y por qué uso uno u otro

2025-01-18 14:56 UTC, evaanngiil commented
@JJ Listo para revisión

2025-01-19 08:59 UTC, JJ requested changes
Ya lo he comentado, pero *hay que resolver todos los comentarios*. El problema de resolverlos sin cambios en la línea comentada es doble
1. Hay que volver a visitar uno por uno todos ellos a ver cómo se han resuelto, haciendo perder el tiempo
2. Una vez que *tú* lo has resuelto, *tú* no lo visitas porque ya crees que lo has resuelto.

2025-01-19 08:59 UTC, JJ commented on docs/testing_testrunner.md
> +En el caso de Java, lo habitual para compilar y ejecutar los tests es usar las herramientas estándar integradas en los sistemas de construcción como Maven o Gradle. Sin embargo, Gradle se destaca por
Sigue sin resolverse con un commit.

2025-01-19 08:59 UTC, JJ commented on docs/testing_testrunner.md
> +### [Spock](https://github.com/spockframework/spock)
No está resuelto con un commit. Si has quitado lo de que "no funciona bien con Java" que creo recordar que es lo que causó el comentario, indica donde.

2025-01-19 08:59 UTC, JJ commented on docs/testing_testrunner.md
> +JUnit 5 es el estándar en Java para la ejecución de pruebas. Según su repositorio en GitHub, cuenta con alta actividad de mantenimiento, con múltiples contribuciones activas y al menos dos versiones
¿En qué sentido es el estándar? ¿Viene en todas las distribuciones? ¿Qué tipo de estándar es?

2025-01-19 08:59 UTC, JJ commented on docs/testing_testrunner.md
> +TestNG, aunque popular en el pasado, ha visto una disminución en su adopción frente a JUnit 5 en proyectos Java típicos y según las métricas de *GitHub*, tiene una actividad algo menor en comparación
Ya puestos, podías haber quitado un poco de "literatura". Con que pongáis lo necesario para justificar la elección es suficiente. Y no, permitir agrupar tests en suits no introduce complejidad, sino que lo simplifica, sobre todo si te da la libertad de ejecutar diferentes suites dependiendo de donde estés.

2025-01-19 08:59 UTC, JJ commented on docs/testing_aserciones.md
> +## Elección de Biblioteca de Aserciones
¿Seguro que Spock no tiene algún tipo de aserciones? Me estás haciendo meterme en el ecosistema de Java más de lo que debería. En todo caso, mira en el Primer de Spock a ver si hubiera algo que se pareciera a unas aserciones.

2025-01-19 08:59 UTC, JJ commented on src/test/java/WishfulGiving/ListaRegalosTest.java
> +    void obtenerRegalosDentroDelPresupuesto() {
No lo has resuelto ni siquiera con un comentario.
Lo siento, este no lo puedo dejar pasar porque era el problema fundamental.

2025-01-19 10:26 UTC, evaanngiil commented on docs/testing_testrunner.md
> +En el caso de Java, lo habitual para compilar y ejecutar los tests es usar las herramientas estándar integradas en los sistemas de construcción como Maven o Gradle. Sin embargo, Gradle se destaca por
Lo explico en https://github.com/evaanngiil/WishfulGiving/pull/26/commits/252968d9dda66f45649be1bab0dedd1f45d7486f

2025-01-19 10:29 UTC, evaanngiil commented on docs/testing_testrunner.md
> +### [Spock](https://github.com/spockframework/spock)
Se explica en https://github.com/evaanngiil/WishfulGiving/pull/26/commits/252968d9dda66f45649be1bab0dedd1f45d7486f

2025-01-19 10:29 UTC, JJ commented on docs/testing_testrunner.md
> +En el caso de Java, lo habitual para compilar y ejecutar los tests es usar las herramientas estándar integradas en los sistemas de construcción como Maven o Gradle. Sin embargo, Gradle se destaca por
De veras, no me hagas esto otra vez, porque *otra vez* tendré que mirar primero en los comentarios *resueltos* y luego en el commit a ver qué es lo que hace. ¿Te parece que la frase que empieza por "Sin embargo" es todavía relevante? ¿O el párrafo entero, para el caso? ¿Quizás deberías decir algo relacionado con que la elección de esta herramienta no es relevante en el ecosistema Java, pero que sí es relevante la elección de otra herramienta diferente?

2025-01-19 10:32 UTC, JJ commented on docs/testing_testrunner.md
> +### [Spock](https://github.com/spockframework/spock)
Te vuelvo a decir lo mismo. Si Spock es a la vez test runner y tiene aserciones, ¿igual poner aquí algo por el estilo de "la parte de test runner de no sé qué" podría resolverlo?
Por otro lado, ¿te parece que poner un commit donde has añadido 46 líneas que responderán a este comentario y a otros 10 me facilita en algo la tarea de revisión? ¿Qué os había dicho *desde el objetivo 2* sobre los commits atómicos?

2025-01-19 10:32 UTC, evaanngiil commented on docs/testing_testrunner.md
> +TestNG, aunque popular en el pasado, ha visto una disminución en su adopción frente a JUnit 5 en proyectos Java típicos y según las métricas de *GitHub*, tiene una actividad algo menor en comparación
Si quito un poco de literatura se me queda en una explicación que no cumpliría ni resolvería los comentarios anteriores, tendrían una gran falta de detalle.

2025-01-19 10:36 UTC, evaanngiil commented on docs/testing_testrunner.md
> +En el caso de Java, lo habitual para compilar y ejecutar los tests es usar las herramientas estándar integradas en los sistemas de construcción como Maven o Gradle. Sin embargo, Gradle se destaca por
Y qué debo hacer exactamente para evitar que mires en los comentarios resueltos y luego en el commit? Se supone que deberíamos resolver comentarios una vez se solucionen con un commit, no? En anteriores objetivos pedías que resolviera ciertos comentarios que no estaban resueltos y yo lo enntendí así, por favor detallame cómo debería ser

2025-01-19 10:38 UTC, evaanngiil commented on docs/testing_testrunner.md
> +### [Spock](https://github.com/spockframework/spock)
Trato de resolverlos todos en un commit por archivo, muchas veces una funcionalidad por archivo. En muchos casos lo que me pide que resuelva se repite varias veces y lo resuelvo con el mismo commit. Prefieres un commit por comentario para que lo puedas corregir mejor?

2025-01-19 10:46 UTC, evaanngiil commented on src/test/java/WishfulGiving/ListaRegalosTest.java
> +    void obtenerRegalosDentroDelPresupuesto() {
he resuelto este comentario en el commit anterior https://github.com/evaanngiil/WishfulGiving/pull/26/commits/0765e1721f04e702b1e508d06901ec7e2329769f

2025-01-19 10:46 UTC, JJ commented on docs/testing_testrunner.md
> +En el caso de Java, lo habitual para compilar y ejecutar los tests es usar las herramientas estándar integradas en los sistemas de construcción como Maven o Gradle. Sin embargo, Gradle se destaca por
Eso deberías saberlo ya.
1. Resolverlos cambiando la línea donde se han hecho
2. Haciendo commits atómicos que se refieran al comentario (y también al issue que resuelvan)
3. Resolviendo *todos* los comentarios de esta forma y no dejándote ninguno.

2025-01-19 10:48 UTC, JJ commented on docs/testing_testrunner.md
> +### [Spock](https://github.com/spockframework/spock)
¿Y a ti te parece que responder a una pregunta con otra pregunta sea la forma más eficiente de emplear el tiempo de los dos?

2025-01-19 10:49 UTC, evaanngiil commented on docs/testing_testrunner.md
> +En el caso de Java, lo habitual para compilar y ejecutar los tests es usar las herramientas estándar integradas en los sistemas de construcción como Maven o Gradle. Sin embargo, Gradle se destaca por
Es decir que para resolver un comentario que hayas puesto tu debo poner el commit donde lo resuelva, en caso contrario no puedo resolverlo

2025-01-19 10:50 UTC, JJ commented on src/test/java/WishfulGiving/ListaRegalosTest.java
> +    void obtenerRegalosDentroDelPresupuesto() {
No, no lo has resuelto. Simplemente porque "obtener regalos dentro del presupuesto" no es lo que pide la HU. 
También has hecho una serie de cambios que están mal y que no tienen relación con esto, pero eso ya te lo comentaré cuando pidas revisión.

2025-01-19 10:53 UTC, JJ commented on docs/testing_testrunner.md
> +En el caso de Java, lo habitual para compilar y ejecutar los tests es usar las herramientas estándar integradas en los sistemas de construcción como Maven o Gradle. Sin embargo, Gradle se destaca por
Evan, o no me estás queriendo entender o efectivamente no estás entendiendo como se resuelven comentarios. Te he dicho las tres formas arriba como se resuelven comentarios. Haz lo que estimes conveniente, y cuando pidas revisión te evaluaré.
Te recuerdo que varias revisiones sin avance (por ejemplo, con comentarios sin resolver) pueden poner en peligro que se pase el objetivo, y que en cualquier caso no parecen la forma más eficiente de emplear ni tu tiempo ni el mío.

2025-01-19 11:02 UTC, evaanngiil commented on src/test/java/WishfulGiving/ListaRegalosTest.java
> +    void obtenerRegalosDentroDelPresupuesto() {
Hay un test que comprueba que se maximiza la satisfaccion del usuario, el test se llama `maximizarSatisfaccion `.

2025-01-19 11:30 UTC, evaanngiil commented on docs/testing_aserciones.md
> +## Elección de Biblioteca de Aserciones
Se indica en la documentacion del testrunner las aserciones de Spock detalladamente. Lo cambio a la documentacion de la biblioteca de aserciones. Eso esta en https://github.com/evaanngiil/WishfulGiving/pull/26/commits/252968d9dda66f45649be1bab0dedd1f45d7486f

2025-01-19 12:23 UTC, JJ commented on src/test/java/WishfulGiving/ListaRegalosTest.java
> +    void obtenerRegalosDentroDelPresupuesto() {
Sigue sin estar resuelto, porque este comentario se refiere a *este* test, a si añade valor al cliente o no. 
En general, deberías considerar que si la persona que te ha hecho un comentario te dice que no está resuelto **es que no lo está** y por lo tanto no deberías marcarlo como resuelto.

2025-01-19 12:54 UTC, evaanngiil commented on docs/testing_aserciones.md
> +## Elección de Biblioteca de Aserciones
En https://github.com/evaanngiil/WishfulGiving/pull/26/commits/252968d9dda66f45649be1bab0dedd1f45d7486f se especifican las aserciones que tiene Spock, sin embargo no deberían estar en la documentación del testrunner, lo muevo a la documentación correspondiente.

2025-01-19 14:15 UTC, evaanngiil commented on docs/testing_testrunner.md
> +TestNG, aunque popular en el pasado, ha visto una disminución en su adopción frente a JUnit 5 en proyectos Java típicos y según las métricas de *GitHub*, tiene una actividad algo menor en comparación
Lo he resumido en https://github.com/evaanngiil/WishfulGiving/pull/26/commits/677ef984659d2a98b70d3f62a1feda3a205dee8b

2025-01-19 14:21 UTC, evaanngiil commented on docs/testing_testrunner.md
> +JUnit 5 es el estándar en Java para la ejecución de pruebas. Según su repositorio en GitHub, cuenta con alta actividad de mantenimiento, con múltiples contribuciones activas y al menos dos versiones
Resuelto y explicado aqui https://github.com/evaanngiil/WishfulGiving/pull/26/commits/4a4fbc4de19c5ac1525e75630d02a6519ba48709

2025-01-19 14:24 UTC, evaanngiil commented on docs/testing_aserciones.md
> +## Elección de Biblioteca de Aserciones
Se resuelve en https://github.com/evaanngiil/WishfulGiving/pull/26/commits/12752d007c39c9979dacb126dea81dfbb6987703

2025-01-19 14:24 UTC, evaanngiil commented on docs/testing_testrunner.md
> +### [Spock](https://github.com/spockframework/spock)
Lo resuelvo en https://github.com/evaanngiil/WishfulGiving/pull/26/commits/12752d007c39c9979dacb126dea81dfbb6987703

2025-01-19 14:31 UTC, evaanngiil commented on src/main/java/WishfulGiving/Regalo.java
> +    public int getPrioridad() {
Explico en https://github.com/evaanngiil/WishfulGiving/pull/26/commits/e4aa3bd1ea34adff725eb8c9504cab076de2ad9b que sí lo requiere la HU y los motivos

2025-01-19 14:31 UTC, evaanngiil commented
@JJ Listo para revision

2025-01-20 07:07 UTC, JJ commented on docs/testing_aserciones.md
> +## Elección de Biblioteca de Aserciones
Vamos a ver, Evan. Podemos hacer esto de forma sencilla o de forma difícil.

La forma sencilla es que trates de entender lo que se te dice y actúes en consecuencia. Este comentario está en un fichero que se llama "testing_aserciones". Te estoy comentando que de las bibliotecas que has considerado, puede que una tenga aserciones también y que **no solo sea un test runner** sino que tenga **una parte de test runner y una parte de aserciones**, y que por tanto, ¿igual sería conveniente que lo incluyeras en esta lista de bibliotecas *que tienen también aserciones*? Y esto porque si se tratara de un framework **que es un test runner** y **además** tiene aserciones, podría ser una opción a considerar, al tener las dos cosas. No has querido entenderlo así, porque no sé si entiendes que lo que se pretende con los comentarios es que el estudiante aprenda, por lo menos a leer la documentación bien y a tomar decisiones informadas.
La forma sencilla habría sido o bien decir "no he entendido qué me quieres decir" o bien hacer un pequeño esfuerzo teniendo en cuenta el contexto y demás, y posiblemente las buenas intenciones del profesor, e incluir aquí algo que dijera "Aserciones de Spock".
Al parecer has decidido no hacerlo así. Me incluyes un commit de 46 líneas, **que modifica otro fichero** que nada tiene que ver con este, donde se ha hecho el comentario, y que entre muchas otras cosas que nada tiene que ver con este comentario, añade **en un fichero donde hablas de test runner** **un ejemplo de aserciones**. Yo entiendo perfectamente que si la postura ante una  corrección no es la de que un profesor pretende que se le enseñe, se ponga cualquier cosa que nada tiene que ver ni con la asignatura, ni con el objetivo, ni en realidad con nada, para mostrar a las claras cuál es la reacción del estudiante ante este simple acto de intentar que el estudiante aprenda.
Entiendo perfectamente también que la reacción sea hacerlo además lo más complicado posible para que el profesor tenga que buscar entre las 46 líneas del commit cuales son las que el estudiante cree que hacen algún cambio relacionado con lo que se comenta aquí. Deberás entender que es realmente complicado hacerlo, ya que lo que pones no tiene nada que ver con la intención de mejora del comentario, ni en realidad con nada. 
Que en el mensaje de commit aparezca "Añade conceptos claves como spec y test engine. Detalla ampliamente el uso de cada test runner con explicaciones detalladas de uso." que no tiene nada que ver con este comentario tampoco no ayuda.
Todo esto lo entiendo. Una reacción comprensible ante un profesor que no tiene ninguna intención de que el estudiante aprenda.
Pero cuando llego al siguiente commit, hecho una hora después, donde borras todo lo relacionado con las posibles aserciones que pudiera tener, "para mudarlo a la documentación correspondiente" ahí ya me pierdo y no entiendo nada. Y si no entiendo nada, no puedo poner ningún comentario ni positivo ni negativo para ayudarte a llegar al objetivo, que, lo creas o no, es mi intención.

**Conclusión**: como en la Wikipedia, asumir la buena fe de la persona que revisa es esencial para entender las correcciones. Para el que revisa, **cambios atómicos** y que pongan en el mensaje de commit qué se soluciona y por qué, o incluso mejor, que se abran issues expresando el problema de un comentario y se cierren con un commit que lo solucione (y siempre en el mensaje de commit por qué se entiende que esa es la solución) es la mejor forma de solucionar los problemas, hacer la solución sencilla y llegar a superar el objetivo.

**Post-conclusión**: tendré que seguir revisando el resto del PR. Al fin y al cabo, que no incluyas una biblioteca de una forma determinada no bloquea el objetivo. La actitud al "resolverlo" sin embargo, sí puede ser un problema para poder llevar yo a cabo una revisión eficiente **y que te ayude**. Se hará lo que se pueda, porque es mi obligación. También dije en el grupo de Telegram de clase que hay compañeros a los que les vendría bien revisar PRs. Te animo a que lo pongas en el grupo de Telegram a ver si alguien se anima.

2025-01-20 07:21 UTC, evaanngiil commented on docs/testing_aserciones.md
> +## Elección de Biblioteca de Aserciones
En la anterior versión que te entregué (https://github.com/evaanngiil/WishfulGiving/commit/252968d9dda66f45649be1bab0dedd1f45d7486f) aparecía ya lo que me pedías que añadieras que eran las aserciones de Spock. Sin embargo, estas no fueron valoradas ya que aparecían en la documentación equivocada (test_runner) por lo que en el siguiente commit las eliminé esa documentación (https://github.com/evaanngiil/WishfulGiving/commit/2aec761bc83a1770ef21823b8d01a58cb3437382) . Si bien es cierto que no he puesto el siguiente commit atómico (tal y como me sugirió en la corrección anterior) pero esto fue ya que en otro comentario aparece el mismo consejo de cambio por lo que lo pongo ahí. El commit del que hablo es  https://github.com/evaanngiil/WishfulGiving/pull/26/commits/8cb930c361208bc751354ab130189def95ec5b2e . 
En el último commit que aparece en esta conversación añado una frase que dice ¨Actúa como un test runner y como una biblioteca de aserciones¨haciendo referencia a lo dicho y posteriormente lo especifico en su documentación correspondiente.

Por otro lado, lo que me refería con no estar enseñándome es referido con su opinión de que lo busque en Google y ponga lo que interprete, y ya después tu me dirás si esta mal o no. Nada que ver con que no busque que aprendamos, se que tiene un grandísimo interés por la asignatura y que le gusta lo que hace y pone todo su empeño en ello.

2025-01-20 07:26 UTC, JJ requested changes
El problema principal sigue siendo que *no se testea la historia de usuario*. Por favor, corrígelo. Ánimo, que ya queda menos.
Te recuerdo que puedes entregar el objetivo 5 en cuanto que pase los tests. Crea como te dije un fichero dummy para el iv.yaml para que no represente un problema los tests de la asignatura. Hazlo también en la rama principal para que no aparezca como ruido en el PR.

2025-01-20 07:26 UTC, JJ commented on docs/testing_aserciones.md
> +## Elección de Biblioteca de Aserciones
Por supuesto, también lo habría hecho fácil que pusieras el commit *de verdad* donde has hecho el cambio: 8cb930c Que también sigue añadiendo más literatura de la cuenta, pero al menos sí entiende lo que se hace. Con un issue y un mensaje de commit adecuado se habría solucionado.
Por favor, cambia esta línea para resolver, por ejemplo quitando mayúsculas Arbitrarias.

2025-01-20 07:26 UTC, JJ commented on docs/testing_aserciones.md
> +### Testing Engines
No te habría costado ningún trabajo abrir un nuevo fichero con esto, que no tiene nada que ver con las aserciones, pero tú mismo.

2025-01-20 07:26 UTC, JJ commented on src/main/java/WishfulGiving/ListaRegalos.java
> +        int n = regalos.size();
¿Te parece que un identificador que se llame `n` es comprensible y permite mantener un código limpio?

2025-01-20 07:26 UTC, JJ commented on src/main/java/WishfulGiving/ListaRegalos.java
> +        int [][] dp = new int [n + 1][capacidad + 1];
¿Y uno que se llame `dp`?

2025-01-20 07:26 UTC, JJ commented on src/main/java/WishfulGiving/ListaRegalos.java
> +                .mapToDouble(Regalo::getPrecio)
Si hay que mapear a double cada vez, ¿por qué no se almacena como double?

2025-01-20 07:26 UTC, JJ commented on src/test/java/WishfulGiving/ListaRegalosTest.java
> +        assertEquals(COSTO_TOTAL_ESPERADO, regalosSeleccionados.stream()
No estás probando que el coste sea mínimo, y por tanto no estás probando si el cliente está satisfecho. Estás probando que la función que has hecho devuelva lo que tú esperas que devuelva. *Siempre* se tiene que testear la historia de usuario. Y probar que minimiza implicaría, al menos, que se ha hecho otra asignación de regalos de alguna forma determinada y que el coste es superior.

2025-01-20 07:26 UTC, JJ commented on src/test/java/WishfulGiving/ListaRegalosTest.java
> +        assertEquals(9, regalosSeleccionados.stream()
Aparte de que estás incluyendo un número mágico, mismo problema que arriba. En todo caso, no me parece que lo de arriba testee la historia de usuario; este sí.

2025-01-20 07:26 UTC, JJ commented on src/test/resources/data/test_regalos.txt
> +# Lista de Juan
Si estás parseando esto, podrías al menos usar algún otro tipo de estructura de datos. Te comento arriba.

2025-01-20 07:26 UTC, JJ commented on src/test/java/WishfulGiving/ListaRegalosTest.java
> +        ListaRegalos lista = listas.get(0);
En el formato *que tú mismo has elegido* figura en una línea el nombre de la persona. ¿Quizás podría haber una forma un poco más estructurada de incluir este nombre?
Por otro lado, tienes dos ejemplos en el fichero, ¿algo que impida que se usen los dos ejemplos?

2025-01-20 07:27 UTC, JJ commented on docs/testing_aserciones.md
> +Un ejemplo de uso podria ser:
¿Te parece que el ejemplo aporta algo a lo de arriba?

2025-01-20 07:27 UTC, JJ commented on docs/testing_aserciones.md
> +- **[Spock](https://github.com/spockframework/spock)**  a diferencia de JUnit, que se centra en aserciones individuales, se centra en describir el comportamiento del sistema bajo prueba a través de b
¿Quizás bastaría con que describieras que estilo de aserciones (de los que vienen en el guión) usa?

2025-01-20 07:30 UTC, JJ commented on docs/testing_aserciones.md
> +## Elección de Biblioteca de Aserciones
Por favor, modifica la línea para resolver este comentario. Por mi parte está resuelto. Y no, yo no te pedía nada. Te vuelvo a repetir que los problemas que crees que se plantean y las posibles soluciones es mejor que las pongáis en un issue y commit lo más atómico posible, porque eso le ahorrará trabajo a todo el mundo. En todo caso, por favor modifica esta línea para resolver el comentario.

2025-01-20 07:32 UTC, JJ commented on docs/testing_aserciones.md
> +## Elección de Biblioteca de Aserciones
> En la anterior versión que te entregué ([252968d](https://github.com/evaanngiil/WishfulGiving/commit/252968d9dda66f45649be1bab0dedd1f45d7486f)) aparecía ya lo que me pedías que añadieras que eran las aserciones de Spock. Sin embargo, estas no fueron valoradas ya que aparecían en la documentación equivocada (test_runner) por lo que en el siguiente commit las eliminé de esa documentación ([2aec761](https://github.com/evaanngiil/WishfulGiving/commit/2aec761bc83a1770ef21823b8d01a58cb3437382)) . Si bien es cierto que no he puesto el siguiente commit atómico (tal y como me sugirió en la corrección anterior) pero esto fue ya que en otro comentario aparece el mismo consejo de cambio por lo que lo pongo ahí. El commit del que hablo es [8cb930c](https://github.com/evaanngiil/WishfulGiving/commit/8cb930c361208bc751354ab130189def95ec5b2e) . En definitiva puede ir viendo progresivamente los cambios y la progresión.

Y no, no se pueden *ir viendo* si no lo pones fácil. Si el commit "mueve", que el commit "mueva". Que no lo borre en uno y lo haga en otro, *que tengo yo que buscar*. Puedes fusionar varios commits en uno usando "squash", eso también podrías aprenderlo porque facilita mucho la revisión al ver sólo el estado inicial y el final.

2025-01-20 23:05 UTC, evaanngiil commented on docs/testing_aserciones.md
> +## Elección de Biblioteca de Aserciones
¿Si fusiono varios commits para indicar que se mueve de un lado y se pone en otro estaría cambiando dos archivos en un mismo commit, no?

2025-01-21 00:17 UTC, evaanngiil commented on src/main/java/WishfulGiving/ListaRegalos.java
> +                .mapToDouble(Regalo::getPrecio)
Se almacena como Double, debe ser que cuando la reescribi pense que era float. Elimino la redundancia

2025-01-21 00:49 UTC, evaanngiil commented on src/test/resources/data/test_regalos.txt
> +# Lista de Juan
No lo parseo, lo ignoro, como se puede ver en el codigo, lo que si es cierto que ese tipo de comentarios aumentan la deuda tecnica. Por otro lado, tambien borro comentarios en el metodo que carga la lista ya que tambien tiene comentarios (no me acostumbro a no ponerlos)

2025-01-21 00:52 UTC, evaanngiil commented on src/test/java/WishfulGiving/ListaRegalosTest.java
> +        ListaRegalos lista = listas.get(0);
No te entiendo bien, figura el nombre de la persona en un comentario pero en la siguiente linea ya aparece de nuevo para ser parseado. No hay nada que impida que se usen los dos ejemplos, la logica incluye que si hay lineas vacias se continue con la lectura hasta que no se encuentre ninguna linea.

2025-01-21 07:02 UTC, JJ commented on docs/testing_aserciones.md
> +## Elección de Biblioteca de Aserciones
"Atómico" no quiere decir "cambiar un solo archivo". Quiere decir "hacer todos los cambios relacionados de una sola vez".

2025-01-21 07:05 UTC, JJ commented on src/test/resources/data/test_regalos.txt
> +# Lista de Juan
Si lo ignoras, ¿como sabes de quién es cada lista?
Por otro lado, sería conveniente que no fuérais más papistas que el papa. Los comentarios *en el código* son un problema. Esto es simplemente un formato arbitrario en el que tienes información semiestructurada, ¿no?

2025-01-21 07:09 UTC, JJ commented on src/test/java/WishfulGiving/ListaRegalosTest.java
> +        ListaRegalos lista = listas.get(0);
El formato lo has puesto tú. Me parecía más razonable antes, que tenía una forma clara de señalar de quién era la lista, que ahora, que hay una primera línea que tiene el mismo formato que las otras pero no el mismo significado.
En todo caso, el problema aquí, aparte de que no usabas todos los ejemplos (no sé si lo harás ahora, ni tampoco entiendo bien por qué pones comentarios sobre temas ya resueltos, pero en fin...) era *cómo* tenías almacenados esos ejemplos, teniendo en cuenta que sólo va a haber una lista de regalos por cada persona.

2025-01-21 07:23 UTC, JJ requested changes
Realmente #29 no es un problema. En [los errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-4.md) pone:

> Los issues deben plantear problemas, igual que en el objetivo 2. El código resuelve el problema, y para ver si se ha resuelto, deben usarse los tests.

En la convocatoria ordinaria, habría habido que empezar de nuevo. Porque si no se corre el peligro de tener código que no se usa, pero sobre todo de escribir código que no soluciona absolutamente nada simplemente porque no sabe qué es lo que tiene que solucionar.

No estamos en la convocatoria ordinaria. Sí te rogaría que trataras de plantear al menos los problemas que se señalan en la última revisión, y que *todas las refactorizaciones de código resultantes* las plantees para resolver esos issues.

Y te recuerdo que el objetivo 5 requiere su tiempo, y que cuanto antes lo entregues, mejor.

2025-01-21 07:23 UTC, JJ commented on src/test/java/WishfulGiving/ListaRegalosTest.java
> +        ListaRegalos listaJuan = listas.get(0);
Seguimos testeando solo uno de los dos ejemplos. ¿Alguna razón para que sea así?

2025-01-21 07:23 UTC, JJ commented on src/main/java/WishfulGiving/GestorListaRegalos.java
>  public class GestorListaRegalos {
¿Dónde estás usando esto?

2025-01-21 07:23 UTC, JJ commented on src/main/java/WishfulGiving/ListaRegalos.java
> +    List<ListaRegalos> listas = new ArrayList<>();
¿Esta indentación es correcta?

2025-01-21 07:23 UTC, JJ commented on src/main/java/WishfulGiving/ListaRegalos.java
> +    public static List<ListaRegalos> cargarListasDeTexto(String filePath) {
¿Quién gestiona esta lista de listas de regalos?
¿Te parece que en la modelización sería más razonable otro tipo de estructura de datos?
Te recuerdo [los errores frecuentes **del objetivo 2**](https://github.com/JJ/IV-/blob/master/errores/objetivo-2.md):

> En cuanto a la entidad, es perfectamente válido empezar a agrupar datos en un objeto valor cuando se va resolviendo un problema específico, poniendo una clave y un valor en un mismo objeto. En general, manejar esto como objetos independientes va a ser sumamente molesto, porque no permite buscar o referirse al objeto por clave, o requiere que se repita la clave en la estructura de datos donde te refieras a ella y en el propio objeto. Las matrices asociativas/hashes/diccionarios o en general estructuras clave-valor permiten modelizar mucho mejor este tipo de dato.

2025-01-21 11:09 UTC, evaanngiil commented on src/test/java/WishfulGiving/ListaRegalosTest.java
> +        ListaRegalos listaJuan = listas.get(0);
No, de hecho podría hasta eliminarlo ya que cree dos ejemplos para que la labor de hacer calculos con los tests sea mucho más rápida.

2025-01-21 15:10 UTC, evaanngiil commented
@JJ  Listo para revisión. He modificado el issue que describía muy por encima el problema que planteaba sobre la lógica de negocio y su testeo. Ahora se plantean todos lo problemas que tenía la propia logica de negocio y se han resuelto con los últimos commits.

2025-01-21 16:24 UTC, JJ approved these changes
:+1: 

Sigue teniendo una buena cantidad de aspectos mejorables, pero en lo esencial está completo.

2025-01-21 16:24 UTC, JJ commented on src/main/java/WishfulGiving/GestorListaRegalos.java
> +    public static GestorListaRegalos cargarListasDeTexto(String filePath) {
¿hay alguna forma de crear la lista que no implique cargarla desde texto? ¿En Java se pueden pasar argumentos a los constructores?

2025-01-21 16:24 UTC, JJ commented on src/main/java/WishfulGiving/GestorListaRegalos.java
> +                String[] partes = line.split(";");
La no presencia de cadenas mágicas sigue siendo un requisito.

2025-01-21 16:24 UTC, JJ commented on src/main/java/WishfulGiving/ListaRegalos.java
> +    public ListaRegalos() {}
¿Esto es obligatorio?

2025-01-23 23:07 UTC, merged